% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{float}
\usepackage{titling}

% Logo's bovenaan
\pretitle{%
  \begin{center}
  \includegraphics[width=4cm]{figures/BINF.png}\hfill
  \includegraphics[width=6cm]{figures/PAIH.png}\\[2cm]
  \huge
}
\posttitle{\end{center}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={In-depth Analysis for Maaseik},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{In-depth Analysis for Maaseik}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Leveraging Data Analytics for Efficient OR Planning at ZOL}
\author{}
\date{\vspace{-2.5em}October 2025}

\begin{document}
\maketitle

\begin{center}
\vspace{2cm}

Niels MARTIN\\
niels.martin@uhasselt.be\\[0.5em]
Maxim RIEBUS\\
maxim.riebus@uhasselt.be\\[0.5em]
Haroon THARWAT\\
haroon.tharwat@uhasselt.be\\

\vspace{6cm}

\textbf{Hasselt University} \\
Faculty of Business Economics \\
Research Group Business Informatics \\
Process Analytics in Healthcare
\end{center}

\newpage
\tableofcontents
\newpage

\section{Introduction}\label{introduction}

Efficient management of operating rooms (ORs) requires an understanding
of how planned surgical activity aligns with real-world execution. This
document provides an in-depth, site-specific analysis for \textbf{Campus
Maaseik}, serving as an analytical extension of the previous exploratory
study. The goal is to systematically address the key research questions
formulated in the project description:

\textbf{Research questions}

\begin{itemize}
\tightlist
\item
  \textbf{Planned versus observed timing}

  \begin{itemize}
  \tightlist
  \item
    How well do the planned operating durations correspond to the actual
    durations?\\
  \item
    What is the typical deviation between the planned start time and the
    actual entry into the operating room?\\
  \item
    Which specialisms or procedure types show the largest differences?\\
  \item
    How do these deviations scale relative to the planned duration
    (proportional or percentage-wise)?
  \end{itemize}
\item
  \textbf{Adherence to working hours}

  \begin{itemize}
  \tightlist
  \item
    How often do procedures run beyond regular working hours (08:00 to
    16:30)?\\
  \item
    What proportion of OR activity occurs in the evening or at night?\\
  \item
    How do these patterns differ between campuses?
  \end{itemize}
\item
  \textbf{Room allocation}

  \begin{itemize}
  \tightlist
  \item
    How often are procedures performed in a different room than
    originally planned?\\
  \item
    Are these reallocations concentrated in specific rooms or
    specialisms?
  \end{itemize}
\item
  \textbf{Urgency and scheduling}

  \begin{itemize}
  \tightlist
  \item
    How are urgent and non-elective cases distributed across campuses
    and time periods?\\
  \item
    To what extent do urgent surgeries overlap with elective activity
    and cause scheduling disruptions?
  \end{itemize}
\end{itemize}

Each of the following sections addresses one of these themes in depth,
focusing on the local characteristics of the Maaseik campus.

\subsection{Unique values and data
richness}\label{unique-values-and-data-richness}

The dataset captures a high degree of heterogeneity in surgical
practice. A total of 33231 unique patient IDs are recorded, spread
across 1016 distinct procedure codes and 1002 procedure names. Surgeon
and anesthesiologist coverage is broad, with 133 and 38 unique
identifiers respectively. These numbers reflect the diversity of
clinical practice at ZOL and underscore the importance of developing
grouping strategies to obtain actionable insights. Table
\ref{tab:uniquevalues} provides an overview of the number of unique
values per variable.

\begin{table}[H]

\caption{\label{tab:unique values}Number of unique values per variable. \label{tab:uniquevalues}}
\centering
\begin{tabular}[t]{lr}
\toprule
Variable & UniqueValues\\
\midrule
PatientID & 33231\\
ProcedureCode & 1016\\
ProcedureName & 1002\\
HeadSurgeonID & 133\\
LengthOfStay & 96\\
\addlinespace
AnesthesiologistID & 38\\
PlannedOR & 12\\
ActualOR & 8\\
Weekday & 7\\
Year & 4\\
\addlinespace
AdmissionType & 3\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Surgical procedure
durations}\label{surgical-procedure-durations}

Operating time is one of the most critical variables for planning.
Procedure durations display wide variation, both within and across
procedure types. Percentile analysis shows that 95\% of all procedures
finish within 115 minutes, 98\% within 148 minutes, 99\% within 178
minutes, and 99.9\% within 294 minutes. While the majority of procedures
are considerably shorter, the long right hand tail in the distribution
indicates the presence of outliers and highly complex cases that drive
variability in scheduling. Figure \ref{fig:duration} illustrates the
distribution of procedure durations, and Table
\ref{tab:durationpercentiles} summarizes the percentile values.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/procedure_durations-1} 

}

\caption{Histogram of Surgery Duration \label{fig:duration}}\label{fig:procedure_durations}
\end{figure}

\newpage

\begin{longtable}[]{@{}lr@{}}
\caption{Percentiles of surgical procedure duration (in minutes).
\label{tab:durationpercentiles}}\tabularnewline
\toprule\noalign{}
Percentile & Duration (minutes) \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Percentile & Duration (minutes) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
95\% & 115 \\
98\% & 148 \\
99\% & 178 \\
99.9\% & 294 \\
\end{longtable}

Looking at the most frequent procedures illustrates the large variation
in operating times. OZ Colonoscopie/Anesthesie -- MK has an average
duration of 16.7 minutes and a median of 16 minutes, while LENSIMPLANT
UNIFOCAAL -- MK averages 25 minutes with a median of 23 minutes.
Transforaminale epidurale infiltratie: lumbaal -- MK typically lasts
11.5 minutes on average with a median of 10 minutes. In contrast, major
orthopedic procedures require far more time. Totale heupprothese DAA --
MK has an average duration of 79.6 minutes and a median of 77 minutes,
and Totale knie prothese robot assisted ROSA -- MK lasts even longer,
with an average of 126.9 minutes and a median of 124 minutes. These
differences highlight the substantial gap in resource requirements
between routine short procedures and complex surgical interventions.
This mix of short standardized cases and long high-complexity operations
underscores the operational challenge of planning an efficient operating
room schedule that accommodates both ends of the spectrum. Table
\ref{tab:top10dur} summarises the ten most frequent procedure types.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.7361}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0972}}@{}}
\caption{Top 10 most frequent procedure types with mean and median
duration \label{tab:top10dur}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Median
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Median
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
OZ Colonscopie/Anesthesie - MK & 8207 & 16.7 & 16 \\
LENSIMPLANT UNIFOCAAL - MK & 5402 & 25.0 & 23 \\
transforaminele epidurale infiltratie : lumbaal - MK & 1738 & 11.5 &
10 \\
FACET RADIOFREQUENCY LUMBAAL - MK & 1559 & 18.0 & 17 \\
TOTALE HEUPPROTHESE DAA - MK & 1480 & 79.6 & 77 \\
FACET DIAGNOSTISCH LUMBAAL - MK & 1329 & 12.2 & 10 \\
PROEFSACRALE INFILTRATIE - MK & 1225 & 10.4 & 9 \\
LENSIMPLANT TORISCH - MK & 1107 & 23.5 & 22 \\
TOTALE KNIE PROTHESE ROBOT ASSISTED ROSA - MK & 764 & 126.9 & 124 \\
EXTRACTIE WHT - MK & 726 & 34.0 & 33 \\
\end{longtable}

\subsection{Admission type and
urgency}\label{admission-type-and-urgency}

The majority of procedures in the dataset are performed in a planned
setting. Ambulatory surgery accounts for 83.9\%, and inpatient
hospitalization for 16.1\%, while emergency admissions represent only
three recorded cases. The urgency classification shows a similar
pattern: 94.3\% of procedures are elective, and 5.7\% are non elective.
Although relatively small in number, the latter category remains
important from a planning perspective, as urgent procedures may disrupt
elective schedules and lead to cancellations or overtime. Table
\ref{tab:admissiontype} and Table \ref{tab:urgencytype} summarize both
distributions.

\begin{longtable}[]{@{}lrr@{}}
\caption{Frequency table for Admission Type
\label{tab:admissiontype}}\tabularnewline
\toprule\noalign{}
AdmissionType & Count & Percentage \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
AdmissionType & Count & Percentage \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
DAG & 45234 & 83.9 \\
HOS & 8665 & 16.1 \\
SPOED & 3 & 0.0 \\
\end{longtable}

\begin{longtable}[]{@{}lrr@{}}
\caption{Frequency table for Urgency Classification
\label{tab:urgencytype}}\tabularnewline
\toprule\noalign{}
UrgencyType & Count & Percentage \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
UrgencyType & Count & Percentage \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
electief & 50811 & 94.3 \\
niet-electief & 3091 & 5.7 \\
\end{longtable}

\subsection{Temporal distribution of
activity}\label{temporal-distribution-of-activity}

Surgical activity is spread consistently across weekdays. Fridays
account for 19.5 percent of weekly activity, Tuesdays for 22.8 percent,
Thursdays for 20.9 percent, Wednesdays each for 17.2 percent, and
Mondays each for 18.4 percent. Weekend days show limited but non
negligible activity, with 0.6 percent of procedures performed on
Saturdays and Sundays. Annual trends reveal steady growth, with the
number of procedures increasing from 14059 in 2022 to 16869 in 2024. At
the time of data extraction, 7258 procedures in 2025 represented 13.5
percent of the total. Together, Table \ref{tab:weekday} and Table
\ref{tab:year} summarize the distribution of surgical activity across
weekdays and years.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1389}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Frequency table for Day of the Week (sorted by descending
count) \label{tab:weekday}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Di & 12308 & 22.8 \\
Do & 11243 & 20.9 \\
Vr & 10503 & 19.5 \\
Ma & 9932 & 18.4 \\
Wo & 9295 & 17.2 \\
Za & 311 & 0.6 \\
Zo & 310 & 0.6 \\
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Frequency table for Year \label{tab:year}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2022 & 14059 & 26.1 \\
2023 & 15716 & 29.2 \\
2024 & 16869 & 31.3 \\
2025 & 7258 & 13.5 \\
\end{longtable}

In summary, procedure durations show strong variability with a long
tailed distribution driven by complex surgeries. The majority of
procedures are elective, while non elective cases still have an
important impact on schedule stability. Activity is distributed somewhat
evenly across weekdays and has grown consistently in recent years. These
findings form the baseline against which more advanced performance
metrics such as start and end deviations, utilization rates, and
predictive models can be developed in subsequent sections of this
report.

\newpage

\section{How accurately does planning reflect reality in the
OR?}\label{how-accurately-does-planning-reflect-reality-in-the-or}

\subsection{Are planned and observed durations
aligned?}\label{are-planned-and-observed-durations-aligned}

The comparison between planned and observed surgery durations shows a
broad spread around the one to one line. Many procedures lie close to
the diagonal, indicating that their observed durations correspond
reasonably well to the planned values. At the same time, a substantial
number of points fall above or below this line, showing that both
underestimation and overestimation occur frequently. Most deviations
appear as longer than planned surgeries, visible in the dense area below
the red dashed line. The dispersion increases for longer procedures,
reflecting greater uncertainty for complex cases. Figure
\ref{fig:planned_vs_observed} displays this relationship.

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/planned vs observed-1} 

}

\caption{Planned vs. Observed Surgery Duration (Maaseik) \label{fig:planned_vs_observed}}\label{fig:planned vs observed}
\end{figure}

On average, surgeries at Maaseik show meaningful variation between
planned and actual durations. Among procedures that last longer than
planned, the mean deviation is 13.9 minutes with a median of 8 minutes,
while shorter cases deviate on average by 9.1 minutes with a median of 6
minutes. The standard deviations of 19.5 minutes and 20.7 minutes
highlight the presence of both moderate deviations and substantial
outliers. While most differences remain within reasonable limits, a
small number of extreme values extend the overall range.

Less than half of all surgeries (39.7\%) take longer than planned, with
an interquartile range of 14 minutes, while 60.3\% finish earlier, with
an interquartile range of 8 minutes. This distribution shows that
deviations occur in both directions, but the spread is larger for cases
that finish earlier. The considerable variability within each category
indicates that although overall planning accuracy is reasonable at the
aggregate level, individual durations remain difficult to predict.
Improving the consistency of duration estimates, particularly for
procedures that frequently deviate, could help reduce daily schedule
variability and limit delays across the operating list. Table
\ref{tab:dur_diff_direction} provides a detailed overview of these
differences.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.2421}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0737}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0947}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0737}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0632}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0632}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0737}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0632}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0632}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0842}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1053}}@{}}
\caption{Difference between actual and planned duration (minutes),
separated by direction \label{tab:dur_diff_direction}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99\_9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percent
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99\_9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percent
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Longer than planned & 13.9 & 8 & 19.5 & 14 & 1 & 378 & 48 & 93 & 182.9 &
39.7\% \\
Shorter than planned & 9.1 & 6 & 20.7 & 8 & 0 & 1308 & 29 & 50 & 106 &
60.3\% \\
\end{longtable}

Expressing deviations as a percentage of the planned duration provides a
standardized view across short and long procedures. Most cases fall
within about ±40 percent of the planned time, indicating a generally
acceptable level of scheduling accuracy in routine practice. The
histogram peaks slightly below zero, showing that surgeries are on
average completed a bit earlier than planned. The shape is roughly
symmetrical, although the right tail extends further, indicating that
large overruns occur less frequently but can be substantial when they
appear. This pattern suggests that while most procedures are reasonably
well estimated, a smaller group of cases contributes disproportionately
to the overall variability in duration accuracy. Figure
\ref{fig:relative_dev} shows the full distribution.

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/relative_deviation_hist-1} 

}

\caption{Distribution of relative deviation between planned and observed duration \label{fig:relative_dev}}\label{fig:relative_deviation_hist}
\end{figure}

Duration deviations differ markedly between admission types. Inpatient,
HOS, cases show the highest variability, with an average deviation of
15.8 percent and a median of 4.1 percent, indicating that these
procedures run longer than planned. With the coefficient of variation of
10.2 signals that deviations vary widely from case to case. This is
typical for the heterogeneous and clinically complex nature of inpatient
surgeries.

Emergency, SPOED, surgeries have an average deviation of 13.1 percent
and a median of minus 63.2 percent. This implies that while a small
number of very long emergency procedures pull the mean upward, the
typical emergency case actually finishes much earlier than planned. The
coefficient of variation of 8 indicates high variability between cases,
implying that some procedures last much longer or shorter than expected.
This reflects the intrinsic clinical uncertainty of acute interventions.

Ambulatory, DAG, surgeries have an average deviation is minus 1.8
percent, the median is minus 8.8 percent, suggesting that most day-case
surgeries run slightly shorter than their planned duration. The
coefficient of variation of minus 26.4 mainly reflects the fact that
even moderate absolute differences translate into larger percentages for
short procedures. These results show that standardized short-stay
procedures are generally estimated accurately in the planning process.
Table \ref{tab:rel_dev_admission} summarizes these patterns.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0769}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2885}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3077}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0865}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0865}}@{}}
\caption{Relative duration deviation and coefficient of variation by
admission type (Maaseik) \label{tab:rel_dev_admission}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
AdmissionType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV (\%)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
AdmissionType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV (\%)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
HOS & 8665 & 15.8 & 4.1 & 161.3 & 10.2 \\
SPOED & 3 & 13.1 & -63.2 & 136.3 & 10.4 \\
DAG & 45234 & -1.8 & -8.8 & 46.3 & -26.4 \\
\end{longtable}

A similar pattern appears when comparing elective and non elective
surgeries. Non elective procedures have an average relative deviation of
24.8 percent and a median of 2.3 percent, with a coefficient of
variation of 10.7, highlighting their unpredictable character. Elective
operations show smaller deviations, with an average of minus 0.4 percent
and a median of minus 6.7 percent. Their coefficient of variation of
minus 123 results from the influence of a small number of extreme
outliers rather than consistent misestimation. Overall, these findings
confirm that while elective cases generally follow expected durations
well, non elective surgeries remain the main source of variability in
the operating schedule. Table \ref{tab:rel_dev_urgency} summarizes these
results.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0769}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2885}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3077}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0865}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0865}}@{}}
\caption{Relative duration deviation and coefficient of variation by
urgency type (Maaseik) \label{tab:rel_dev_urgency}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
UrgencyType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV (\%)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
UrgencyType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median relative deviation (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV (\%)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
niet-electief & 3091 & 24.8 & 2.3 & 264.4 & 10.7 \\
electief & 50811 & -0.4 & -6.7 & 45.8 & -123 \\
\end{longtable}

The mean relative deviation between planned and observed durations
remains broadly stable over the observed years. In 2022 the average
deviation is 2.6 percent, decreasing slightly to 2.3 percent in 2023. A
clearer decline appears in 2024, reaching minus 0.3 percent, while the
partial data for 2025 show a decrease to minus 1.5 percent.

This pattern indicates that planning accuracy at Maaseik has remained
relatively consistent over time, with moderate year to year decline. The
differences are small and likely reflect normal operational variation
rather than systematic changes in planning quality. Overall, the
stability of the yearly averages suggests surguries are finishing
slightly shorter than planned, but the effect size is small and should
not be overstated. Figure \ref{fig:reldev_year} illustrates these
trends.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/rel_duration_dev_year-1} 

}

\caption{Relative duration deviation by year \label{fig:reldev_year}}\label{fig:rel_duration_dev_year}
\end{figure}

The relative deviation between planned and observed durations remains
stable throughout the regular workweek, with mean deviations ranging
from minus 2.4 percent to 2.8 percent. This consistency indicates
limited variation in planning accuracy across Monday to Friday. Small
fluctuations, such as the slightly higher averages on Tuesday and Friday
or the lower values on Wednesday and Thhursday, likely reflect
differences in case mix rather than structural scheduling issues.

A clear contrast appears during the weekend. On Saturdays and Sundays
the mean deviations rise sharply to 17.7 percent and 18.7 percent, far
above weekday levels. These higher discrepancies reflect the different
operating context of weekend surgery, where volumnes are low and cases
are more often acute and unplanned. Weekend surgeries are typically non
elective, often requiring flexible resource allocation and showing less
predictable durations. The weekday weekend contrast therefore highlights
the stability of elective scheduling during standard operating days and
the inherent variability associated with emergency work at the end of
the week. Figure \ref{fig:reldev_weekday} summarizes these differences.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/rel_dev_weekday-1} 

}

\caption{Relative deviation by weekday \label{fig:reldev_weekday}}\label{fig:rel_dev_weekday}
\end{figure}

Variation in deviation differs considerably across operating rooms. The
largest average deviations are concentrated in the complex surgery rooms
of the MO block, most notably MO03, where the mean absolute deviation is
22.5 minutes and 56.6 percent of cases run longer than planned. Other
high variability rooms such as MO05, MO04, and MO01 also show average
deviations between 15.5 and 18.1 minutes, reflecting the higher
uncertainty typical of lengthy or technically demanding procedures.

By contrast, rooms such as MKI1 and MKI3, mainly associated with short
and standardized interventions, display mean deviations around 6 minutes
and a higher share of shorter than longer cases. These differences
illustrate how the degree of procedural complexity and specialization
strongly influences planning precision. Table \ref{tab:ordeviation_or}
provides the detailed overview.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0917}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0667}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1083}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2417}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1167}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2500}}@{}}
\caption{Duration deviations per operating room, ordered by mean
absolute deviation \label{tab:ordeviation_or}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean abs dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Longer (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative dev (longer)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Shorter (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative dev (shorter)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean abs dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Longer (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative dev (longer)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Shorter (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean relative dev (shorter)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO03 & 4566 & 22.5 & 56.6 & 48 & 41.2 & -21.5 \\
MO05 & 4512 & 18.1 & 45.2 & 37.5 & 52.6 & -23.7 \\
MO04 & 5491 & 16.4 & 42.1 & 35.1 & 55.4 & -22.6 \\
MO01 & 4063 & 15.5 & 42.9 & 33.1 & 54.8 & -23.8 \\
MO06 & 4552 & 14 & 48.8 & 45.7 & 48 & -23 \\
MO02 & 8293 & 6.6 & 39.5 & 35.2 & 53.9 & -20.9 \\
MKI1 & 8262 & 6.1 & 43.7 & 44.2 & 50.2 & -32.4 \\
MKI3 & 14163 & 6.1 & 25.6 & 45.1 & 68.9 & -33.4 \\
\end{longtable}

Among the most extreme deviations in surgery duration, overruns remain
the predominant direction. Around 81.7 percent of the top one percent of
deviations correspond to procedures that last longer than planned, while
18.3 percent finish earlier than expected. This indicates that large
underestimations still occur

Although both directions are represented among the extreme cases, their
operational impact remains different. Early finishes generally create
limited idle time, whereas overruns can delay subsequent cases and
increase the likelihood of overtime. The presence of both substantial
overruns and substantial early completions in the extreme group suggests
that large deviations, regardless of direction, contribute meaningfully
to schedule variability. This reinforces the importance of monitoring
procedure types that exhibit high relative uncertainty, as both
underestimation and overestimation can materially affect workflow
stability. Table \ref{tab:extreme_dir} summarizes these results.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3194}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Direction of deviation among the 1\% most extreme cases
(Masseik) \label{tab:extreme_dir}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Longer than planned & 443 & 81.7\% \\
Shorter than planned & 99 & 18.3\% \\
\end{longtable}

\subsection{A closer look on the coefficient of
variation}\label{a-closer-look-on-the-coefficient-of-variation}

The monthly coefficient of variation for planning deviation shows clear
fluctuations over time without evidence a consistent long term upward or
downward trend. As shown in Figure \ref{fig:cv_planning}, early 2022
begins at relatively low variability levels near 1.2 to 1.5. Through the
remainder of 2022 the values move mostly between 1.3 and 1.9, indicating
modest dispersion in planning deviations.

During 2023 the pattern becomes more irregular, with several months
reaching values between about 2.5 and 3.5, although lower values around
1.3 also occur. This results in a more irregular pattern rather than a
continuous increase. In early 2024 the coefficient peaks briefly above
3.25, marking the largest monthly value in the series. After this spike
the metric decreases again and fluctuates between roughly 1.3 and 2.5
during the remainder of 2024.

In 2025 the values settles into a narrower band around 1.5 to 2.75,
showing moderate variability. Taken together, these fluctuations
indicate that the coefficient of variation is driven more by short term
shifts in procedure mix and occasional months with small mean deviations
than by systematic changes in planning accuracy. Most months fall within
a moderate range, while the isolated spikes signal periods of heightened
dispersion rather than long term trends.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/cv_monthly-1} 

}

\caption{Monthly evolution of coefficient of variation (Planning deviation) \label{fig:cv_planning}}\label{fig:cv_monthly}
\end{figure}

\subsubsection{Variability by planned duration
group}\label{variability-by-planned-duration-group}

Variation in surgical timing can be examined from two complementary
perspectives that describe different aspects of performance. The first
is the coefficient of variation of observed duration, calculated as the
standard deviation divided by the mean of the observed surgical times.
This indicator expresses how dispersed the recorded durations are
relative to their average. In a dataset such as this one, which contains
a mix of both short and long operations, the magnitude of this
coefficient is driven primarily by the structural heterogeneity of the
case mix rather than by instability within individual cases.

The second perspective is the coefficient of variation of the planning
deviation, which measures the consistency of planning accuracy. It is
computed as the standard deviation of the absolute deviation between
planned and observed time, divided by the mean of that deviation. Unlike
the first measure, this coefficient isolates how variable planning
errors are, independent of the underlying diversity in surgical
duration.

Together, these indicators separate two sources of variability: the
inherent spread in surgical case lengths and the irregularity of
scheduling precision. Understanding how these two behave provides
insight into whether deviations arise mainly from the diversity of
surgical activity or from planning inconsistency. Table
\ref{tab:cv_group} summarises these metrics across five duration
categories and forms the basis for the category specific analyses that
follow.

The summary statistics confirm a clear scaling effect in relative
variability. The coefficient of variation of observed durations
decreases as planned duration increases: procedures planned for less
than 30 minutes have a CV of 0.6036042, procedures in the 31--60 minute
group show 0.4727512, the 61--90 minute group 0.3614345, the 91--180
minute group 0.3480405, and the longest category over 180 minutes shows
0.3700689. This pattern is consistent with the fact that shorter cases
amplify small absolute fluctuations when expressed relative to their
mean, while longer cases distribute absolute variation over a broader
time base.

For the planning deviation, coefficients of variation are considerably
higher across all groups, reflecting the larger proportional spread in
the differences between planned and actual duration. These values range
from 1.2314398 in the shortest category to 1.0728840 in the 31--60
minute group, 1.0520157 in the 61--90 minute group, 0.9782855 in the
91--180 minute group, and 1.9709173 in procedures lasting more than 180
minutes. This pattern suggests that longer and more complex procedures,
while not necessarily less stable in execution, exhibit greater
variation in planning accuracy.

Together, these figures show that relative variability in observed
duration is largely structural and reflects case mix composition,
whereas variability in planning deviation captures the irregularity in
scheduling precision. The distinction between the two metrics provides
the foundation for the next analyses, which explore how these patterns
manifest within each duration category and across operating rooms.

\begin{table}

\caption{\label{tab:cv group}Summary of mean duration, SD, and CV by planned duration group (Observed vs. Planning deviation) \label{tab:cv_group}}
\centering
\begin{tabular}[t]{lrrrrrrr}
\toprule
Group & n & Mean duration & SD duration & CV duration & Mean planning & SD planning & CV planning\\
\midrule
<30 & 32669 & 19.13205 & 11.54819 & 0.6036042 & 6.394839 & 7.874859 & 1.2314398\\
31–60 & 9553 & 44.66314 & 21.11455 & 0.4727512 & 12.646289 & 13.568001 & 1.0728840\\
61–90 & 7216 & 75.52841 & 27.29858 & 0.3614345 & 18.165604 & 19.110501 & 1.0520157\\
91–180 & 4174 & 114.70316 & 39.92135 & 0.3480405 & 25.487302 & 24.933858 & 0.9782855\\
> 180 & 290 & 216.17586 & 79.99996 & 0.3700689 & 91.668965 & 180.671951 & 1.9709173\\
\bottomrule
\end{tabular}
\end{table}

The monthly evolution of the coefficient of variation for observed
durations shows stable and clearly separated patterns between the
planned duration groups. Short procedures in the \textless30 minute
category consistently display the highest relative variability, with
values generally between 0.55 and 75 and an isolated spike close to 0.9.
Procedures in the 31--60, typically around 0.45 to 0.55. The 61--90 and
91--180 minute groups cluster at lower levels, mostly between 0.30 and
0.40. Procedures longer than 180 minutes display much stronger month to
month swings, with coefficients ranging roughly from 0.05 to 0.60; this
group alternates between being the least and one of the more variable
categories. Overall, the relative ordering of variability by planned
duration is stable over time, with short procedures showing the highest
proportional dispersion and mid range durations the lowest. Figure
\ref{fig:cv_obs_group} illustrates these monthly patterns across
duration groups.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/cv obs group-1} 

}

\caption{Monthly evolution of coefficient of variation (Observed durations) \label{fig:cv_obs_group}}\label{fig:cv obs group}
\end{figure}

The coefficient of variation of planning deviation exhibits noticeably
stronger fluctuations over time than the coefficient of variation of
observed durations. While most duration groups remain centred around
values close to 1.0, the amplitude of month-to-month variation differs
substantially across categories. The longest procedures (\textgreater180
minutes) show the most pronounced volatility, with coefficients ranging
from below 0.5 to peaks above 2.3. This pattern likely reflects both the
small number of long cases in many months---making the measure sensitive
to denominator effects---and the inherent unpredictability of complex
procedures. Shorter procedures (\textless30 minutes) also display
visible fluctuation, with values typically around 1.0--1.4 and
occasional peaks approaching 2.1. These variations suggest that even
small absolute planning errors can produce relatively large proportional
deviations for very short surgeries. By contrast, the mid-range groups
(31--60, 61--90, and 91--180 minutes) form a more stable band, with
coefficients generally between 0.6 and 1.3 and far fewer extreme spikes.
This indicates that planning accuracy for medium-duration procedures is
relatively consistent across months. Figure \ref{fig:cv_planning_group}
shows how these patterns evolve monthly across the duration groups.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/cv planning group-1} 

}

\caption{Monthly evolution of coefficient of variation (Planning deviation) \label{fig:cv_planning_group}}\label{fig:cv planning group}
\end{figure}

Viewed together, the two figures show a clear contrast between the
stability of observed surgical durations and the variability of planning
accuracy. The coefficient of variation for observed durations remains
structurally stable across months and duration categories, with each
group maintaining a consistent relative position over time. In contrast,
the coefficient of variation for planning deviation fluctuates more
markedly, particularly for the shortest and longest procedure groups,
where month-to-month swings are more pronounced. These contrasting
patterns suggest that the execution of surgical procedures is relatively
consistent, while planning accuracy is more sensitive to shifts in case
mix, sample size effects, or variations in procedural complexity. The
following sections explore these dynamics in greater depth by analyzing
each duration group individually and comparing the distribution of
coefficients of variation across operating rooms.

\vspace{1em}

\noindent\textbf{Surgeries planned under 30 minutes} \vspace{0.5em}

Short procedures, typically representing high volume and standardized
interventions, show moderate relative variability across operating
rooms. For this category, coefficients of variation of observed
durations range roughly between 0.39 and 0.61, which reflects the
proportional impact of small absolute timing fluctuations on short
cases. These values are expected for brief procedures, where even
limited variation translates into relatively large coefficients once
expressed relative to their mean duration. Table \ref{tab:cv_room_lt30}
summarises these indicators for all rooms with at least eleven surgeries
in this duration group.

Across operating rooms, the pattern is broadly homogeneous. Rooms such
as MKI3, MO04, and MO05 display higher CV values in the range of
0.57--0.61, while others, including MO02 and MO06, lie toward the lower
end between 0.39 and 0.52. These differences are modest and primarily
reflect variation in the specific mix of short procedures allocated to
each room rather than substantive disparities in execution consistency.

For the coefficient of variation of planning deviation, values are
systematically higher and exhibit a wider spread, with most rooms
falling between roughly 0.93 and 1.37. This indicates that proportional
variability in planning accuracy exceeds that of the observed durations
themselves. Lower planning deviation CVs appear in rooms such as MKI3
and MO01, whereas higher values are found in rooms including MO02 and
MO05.These differences likely stem from variation in case composition
and the sensitivity of the CV metric when mean deviations are small.

Taken together, short procedures show consistent execution profiles and
broadly similar planning accuracy across rooms. The relatively high
coefficients primarily reflect proportional scaling effects inherent to
short interventions rather than meaningful operational instability. The
next sections examine whether these patterns persist for procedures of
longer planned duration, where absolute variability becomes more
influential and planning precision may pose greater challenges.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0864}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0988}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1975}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1728}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1728}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1358}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1358}}@{}}
\caption{Coefficient of variation per operating room for surgeries
planned \textless30 minutes (only rooms with \textgreater10 surgeries
shown) \label{tab:cv_room_lt30} (continued below)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MKI3 & 13093 & 14.55 & 8.414 & 0.5784 & 5.669 & 5.321 \\
MKI1 & 8241 & 16.68 & 9.028 & 0.5411 & 5.844 & 7.182 \\
MO02 & 7301 & 24.53 & 9.577 & 0.3904 & 5.782 & 7.488 \\
MO06 & 1074 & 30.42 & 15.59 & 0.5127 & 10.3 & 12.5 \\
MO01 & 866 & 24.61 & 13.19 & 0.536 & 8.555 & 8.608 \\
MO04 & 840 & 25.99 & 15.16 & 0.5832 & 9.743 & 12.24 \\
MO03 & 697 & 37.28 & 20.32 & 0.5451 & 16.64 & 17.52 \\
MO05 & 557 & 29.03 & 17.64 & 0.6074 & 10.91 & 14.89 \\
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 0\tabcolsep) * \real{0.1250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0.9387 \\
1.229 \\
1.295 \\
1.214 \\
1.006 \\
1.256 \\
1.053 \\
1.365 \\
\end{longtable}

\vspace{1em}

\noindent\textbf{Surgeries planned 31–60 minutes} \vspace{0.5em}

Procedures with a planned duration of 31--60 minutes show moderate and
relatively uniform variability across operating rooms. For this
category, the coefficients of variation of observed durations cluster
between approximately 0.41 and 0.51, as reported in Table
\ref{tab:cv_room_31_60}. The highest values appear in MO04 (0.5149),
MO05 (0.4832), and MO01 (0.4562), while several rooms, including MO02
(0.4144), MO06 (0.4264), and MO03 (0.4365), show lower variability.
Higher values appear in rooms such as MO04 (0.5149), MO05 (0.4832), and
MO01 (0.4562), while rooms including MO02 (0.4144), MO06 (0.4264), and
MO03 (0.4365) show slightly lower dispersion. These differences are
modest and likely reflect variation in the composition of procedures
performed in each room rather than systematic differences in execution
stability.

The coefficients of variation for planning deviation are consistently
higher, ranging from roughly 0.87 to 1.12 across rooms. As shown in
Table \ref{tab:cv_room_31_60}, the lowest CV values appear in rooms such
as MO02 (0.8763) and MKI3 (0.9102), while larger or multipurpose rooms
including MO03 (1.122) and MO06 (1.077) show higher values. This
indicates that proportional variability in planning accuracy exceeds
that of the observed durations, although the degree of dispersion
remains moderate and relatively uniform across the operating suite.

Taken together, these results show that procedures planned for 31--60
minutes display consistent execution times and moderate variation in
planning accuracy across operating rooms. The observed coefficients
largely follow proportional scaling effects typical of medium-length
procedures rather than substantial operational differences.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1839}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1264}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}@{}}
\caption{Coefficient of variation per operating room for surgeries
planned 31--60 minutes (only rooms with \textgreater10 surgeries shown)
\label{tab:cv_room_31_60}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO06 & 2432 & 46.27 & 19.73 & 0.4264 & 11.97 & 12.89 & 1.077 \\
MO03 & 1380 & 52.7 & 23 & 0.4365 & 14.55 & 16.33 & 1.122 \\
MO05 & 1340 & 45.2 & 21.84 & 0.4832 & 13.51 & 14.48 & 1.072 \\
MO01 & 1334 & 43.67 & 19.92 & 0.4562 & 11.58 & 12.41 & 1.071 \\
MO04 & 1153 & 46.51 & 23.95 & 0.5149 & 14.94 & 16.1 & 1.077 \\
MKI3 & 1036 & 31.74 & 14.38 & 0.4532 & 11.13 & 10.13 & 0.9102 \\
MO02 & 874 & 41.07 & 17.02 & 0.4144 & 10.61 & 9.294 & 0.8763 \\
\end{longtable}

\vspace{1em}

\noindent\textbf{Surgeries planned 61–90 minutes} \vspace{0.5em}

Procedures planned between 61 and 90 minutes represent a balanced
segment of the surgical workload, combining moderately complex inpatient
cases with standardized elective interventions. Within this group, the
coefficient of variation of observed durations is relatively low and
stable across operating rooms. As shown in Table
\ref{tab:cv_room_61_90}, most rooms display CV values between 0.27 and
0.57, indicating proportionally consistent execution times once
procedures of this length begin. The limited dispersion suggests that
mid-length operations, often supported by standardized preparation and
anaesthesia routines, show predictable timing.

Differences between rooms are modest. Lower CVs appear in MO04 (0.2558),
MO01 (0.3457), and MO05 (0.3562), while higher values emerge in MO02
(0.4981) and MO03 (0.4344). The highest variability is observed in MKI3
(0.5668), a room that accommodates a broader mix of procedures. These
differences likely reflect variations in case composition rather than
underlying differences in workflow reliability.

The coefficient of variation of planning deviation follows a similar but
slightly broader distribution. Most rooms show CV\_deviation levels
between 0.27 and 1.3, indicating moderate variation in planning
accuracy. As shown in Table \ref{tab:cv_room_61_90}, rooms such as MKI1
(0.2718) and MKI3 (0.4576) show lower CV values, while others, including
MO04 (0.9475) and MO03 (1.294), display higher dispersion in planning
deviation. These patterns suggest that although mean estimates are
generally accurate, deviations vary more widely for some case mixes.

Overall, procedures in the 61--90 minute category show stable and
proportional execution times with only limited variation across
operating rooms. Planning accuracy exhibits moderate dispersion but
remains broadly consistent across the complex. Compared with shorter
procedures, these mid-length cases are less affected by proportional
scaling effects and offer a relatively steady anchor point within the
daily schedule.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1839}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1264}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}@{}}
\caption{Coefficient of variation per operating room for surgeries
planned 61--90 minutes (only rooms with \textgreater10 surgeries shown)
\label{tab:cv_room_61_90}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO04 & 2441 & 74.73 & 20.6 & 0.2757 & 14.87 & 14.09 & 0.9475 \\
MO03 & 1610 & 78.98 & 34.31 & 0.4344 & 20.26 & 26.22 & 1.294 \\
MO05 & 1401 & 73.4 & 26.15 & 0.3562 & 19.12 & 17.78 & 0.9299 \\
MO01 & 903 & 81.93 & 28.32 & 0.3457 & 20.08 & 18.34 & 0.9135 \\
MO06 & 715 & 71.94 & 25.7 & 0.3572 & 18.33 & 16.81 & 0.9171 \\
MO02 & 99 & 57.46 & 28.62 & 0.4981 & 23.97 & 16.32 & 0.6809 \\
MKI3 & 34 & 37.35 & 21.17 & 0.5668 & 34.18 & 15.64 & 0.4576 \\
MKI1 & 13 & 17.38 & 6.727 & 0.387 & 45.85 & 12.46 & 0.2718 \\
\end{longtable}

\vspace{1em}

\noindent\textbf{Surgeries planned 91–180 minutes} \vspace{0.5em}

Surgeries with a planned duration between 91 and 180 minutes encompass
complex elective procedures as well as major inpatient operations.
Within this category, the coefficient of variation of observed durations
is moderate and shows limited variation across operating rooms. As
reported in Table \ref{tab:cv_room_91_180}, most rooms exhibit CV values
between 0.30 and 0.37, indicating proportionally stable execution times
despite the broader absolute duration range typical of these cases. The
lowest coefficients appear in MO05 (0.3036) and MO04 (0.3295), while
MO03 (0.4321) displays the highest value in this group, likely
reflecting a more heterogeneous case mix. Overall, these differences
remain modest and suggest consistent timing performance across rooms.

The coefficient of variation of planning deviation shows a similarly
compact distribution. Most rooms fall between 0.63 and 0.94, with the
lowest value observed in MO02 (0.63) and higher values in MO03 (1.204)
and MO05 (0.9404). Although planning deviation CVs are uniformly higher
than the CVs of observed duration, the spread across rooms remains
limited, as expected in this category. This pattern indicates that
planning accuracy for mid- to long-duration surgeries is reasonably
stable, even when procedure complexity varies.

Taken together, both indicators show restrained variability, suggesting
that once procedures reach the 91--180 minute range, timing performance
becomes comparatively predictable. Relative variation in both observed
duration and planning deviation diminishes as the absolute operation
time increases, making this segment one of the more consistent
components of the surgical program from a timing perspective.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0805}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1839}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1609}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1264}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1034}}@{}}
\caption{Coefficient of variation per operating room for surgeries
planned 91--180 minutes (only rooms with \textgreater10 surgeries shown)
\label{tab:cv_room_91_180}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO05 & 1205 & 117 & 35.51 & 0.3036 & 23.94 & 22.51 & 0.9404 \\
MO04 & 1043 & 111 & 36.56 & 0.3295 & 25.32 & 22.07 & 0.8718 \\
MO01 & 958 & 107 & 35.57 & 0.3325 & 22.51 & 18.23 & 0.8096 \\
MO03 & 634 & 124 & 53.6 & 0.4321 & 32.21 & 38.77 & 1.204 \\
MO06 & 315 & 122.2 & 40.5 & 0.3315 & 27.08 & 22.46 & 0.8294 \\
MO02 & 18 & 128.9 & 47.28 & 0.3668 & 30.94 & 19.5 & 0.63 \\
\end{longtable}

\vspace{1em}

\noindent\textbf{Surgeries planned over 180 minutes} \vspace{0.5em}

Procedures with a planned duration exceeding three hours represent the
most complex and resource-intensive segment of the surgical program.
Within this group, the coefficient of variation of observed durations
remains moderate across operating rooms. As shown in Table
\ref{tab:cv_room_over180}, CV values range from 0.321 in MO03 to 0.473
in MO06, with MO04 lying in between at 0.405. These values indicate
that, despite the inherent heterogeneity and longer absolute times of
these procedures, their proportional variability remains stable across
rooms.

The coefficient of variation of planning deviation shows a wider spread,
reflecting the greater difficulty of estimating the duration of lengthy
and complex operations. CV\_dev ranges from 1.62 in MO04 to 2.087 in
MO03, with MO06 also exhibiting a high value of 1.742. These elevated
coefficients primarily reflect the large absolute differences between
planned and actual durations that tend to arise in very long procedures,
rather than systematic inconsistencies in scheduling accuracy.

Taken together, the results suggest that surgeries lasting more than
three hours display relatively uniform proportional duration patterns
across operating rooms. Observed durations show limited relative
variability, while planning deviations exhibit broader dispersion
consistent with the uncertainty inherent to long and complex surgical
interventions. The higher coefficients in some rooms likely reflect
small sample sizes or concentration of rare, high-complexity cases
rather than persistent operational issues.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0814}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0698}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1860}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1628}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1628}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1279}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1047}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1047}}@{}}
\caption{Coefficient of variation per operating room for surgeries
planned \textgreater{} 180 minutes (only rooms with \textgreater10
surgeries shown) \label{tab:cv_room_over180}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD dev
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
CV dev
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO03 & 245 & 227.4 & 73 & 0.321 & 73.8 & 154 & 2.087 \\
MO06 & 16 & 176.5 & 83.49 & 0.473 & 130.7 & 227.6 & 1.742 \\
MO04 & 14 & 176.9 & 71.66 & 0.405 & 156.2 & 253 & 1.62 \\
\end{longtable}

\subsubsection{Relationship between variability and mean operative
duration}\label{relationship-between-variability-and-mean-operative-duration}

Examining how variability scales with operative duration provides
insight into whether dispersion in surgical times increases
proportionally with the length of a procedure. By analysing this
relationship at the level of procedure types, it becomes possible to
distinguish structural scaling effects from differences in planning
performance. The following figures present three complementary
perspectives: the standard deviation of operative duration, the
coefficient of variation of observed duration, and the coefficient of
variation of planning deviation. Together, they describe how both
absolute and relative variability evolve as surgeries become longer or
more complex.

Figure \ref{fig:sd_mean_relation} shows a clear positive relationship
between mean operative time and its standard deviation across procedure
types. As average duration increases, the absolute spread of observed
times also increases, and the fitted regression line indicates that this
expansion occurs in a roughly proportional manner. This pattern reflects
a natural scaling effect: longer procedures inherently allow for larger
absolute deviations while still maintaining a similar proportional
variability. In the scatterplot, procedures clustered around 50--100
minutes typically exhibit standard deviations of 20--40 minutes, whereas
operations with mean durations above 150 minutes often show standard
deviations of 50 minutes or more. A very long procedure exceeding 250
minutes displays even greater dispersion, consistent with the larger
range of potential intraoperative complexity.

Importantly, this linear trend does not imply that longer procedures are
relatively more unpredictable. Instead, it shows that absolute
variability increases with case duration, while relative variability may
remain stable or even decrease, as demonstrated earlier in the
coefficient-of-variation analyses. The figure therefore highlights that
differences in standard deviation alone cannot be used to infer poorer
timing control for longer surgeries; the observed increase simply
mirrors the scaling of operative time itself.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/sd mean relation-1} 

}

\caption{Standard deviation in operative time relative to mean duration \label{fig:sd_mean_relation}}\label{fig:sd mean relation}
\end{figure}

When variability is expressed relative to mean duration, a clear inverse
relationship appears, as shown in Figure \ref{fig:cv_mean_relation}. The
coefficient of variation decreases progressively as procedures become
longer, indicating that proportional dispersion narrows with increasing
case length. Shorter procedures frequently exhibit CV values above 0.6,
and several exceed 0.8 or 1.0, whereas most long procedures fall well
below 0.4, with many clustering near 0.25. This pattern reflects a
fundamental scaling property of surgical duration data. Although longer
procedures show larger absolute variability as demonstrated in the
previous figure their variability grows more slowly than their mean
duration. As a result, longer cases appear proportionally more stable
relative to their expected duration, while short procedures amplify even
modest absolute deviations into larger relative differences. Overall,
the figure confirms that relative unpredictability decreases with
increasing procedure length, complementing the earlier observation that
absolute variability rises as surgeries become longer.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/cv mean relation-1} 

}

\caption{Coefficient of variation (operative duration) relative to mean duration \label{fig:cv_mean_relation}}\label{fig:cv mean relation}
\end{figure}

A similar inverse pattern appears when plotting the coefficient of
variation of planning deviation against mean operative duration, as
shown in Figure \ref{fig:cv_planning_relation}. For short procedures,
the relative spread in planning deviations is large, with some CV values
rising above 3.0 and, in a few cases, approaching 5.0. These extreme
coefficients arise because even small absolute deviations in planning
translate into large proportional differences when the planned duration
is short.

As procedure length increases, this proportional amplification weakens.
Procedures with mean durations above roughly 100 minutes tend to cluster
around CV values close to or below 1.0, reflecting a more stable
relationship between planned and observed duration in relative terms.
Although the scatter remains wide, the downward slope in the fitted line
shows that the proportional variability in planning deviation decreases
gradually as surgeries become longer. This trend reflects the same
underlying scaling principle observed for operative duration: absolute
deviations grow with procedure length, but not quickly enough to
increase proportional variability. Consequently, the negative slope
therefore reflects the same scaling principle observed for operative
duration, rather than a systematic improvement in planning accuracy.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/cv planning relation-1} 

}

\caption{Coefficient of variation (planning deviation) relative to mean duration \label{fig:cv_planning_relation}}\label{fig:cv planning relation}
\end{figure}

Taken together, the three figures demonstrate a consistent pattern:
absolute variability in operative time increases as procedures become
longer, while relative variability decreases. As case length grows,
standard deviations expand in absolute terms, but this growth is slower
than the increase in mean duration. The result is that proportional
uncertainty is highest for short procedures where even minor timing
differences constitute a large share of total duration and lowest for
long surgeries, where absolute deviations are spread over a much larger
time base. This structural scaling effect explains why longer operations
appear more stable in relative terms, despite exhibiting wider absolute
ranges.

\subsection{How large are start-time delays, and when do they
happen?}\label{how-large-are-start-time-delays-and-when-do-they-happen}

Start-time deviations exhibit substantial variability, with late starts
occurring more frequently and with slightly greater magnitude than early
ones. As shown in Table \ref{tab:start_diff}, 65.3 percent of surgeries
begin later than scheduled, with a mean delay of 39.1 minutes and a
median of 25 minutes. Early starts account for the remaining 34.7
percent, averaging 27.5 minutes ahead of plan and a median of 16
minutes.

The dispersion in both directions is considerable. Standard deviations
reach 53.3 minutes for late starts and 47.7 minutes for early starts,
indicating broad day-to-day fluctuations in punctuality. A small number
of extreme outliers extend far beyond the typical range, with the
largest delays exceeding 1,700 minutes and the earliest starts
surpassing 1,200 minutes, underscoring the presence of rare but very
large scheduling deviations. Overall, these results confirm that
punctuality at the beginning of the surgical day remains a significant
operational challenge. Late starts are more common and can propagate
delays across subsequent cases, reducing room efficiency and compressing
already constrained schedules.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1628}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0814}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1047}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0814}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0698}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0698}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0814}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0698}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0698}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0930}}
  >{\centering\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1163}}@{}}
\caption{Difference between actual and planned start time (absolute
minutes), separated by direction \label{tab:start_diff}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99.9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percent
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
direction
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99.9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percent
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Late start & 39.1 & 25 & 53.3 & 43 & 1 & 1765 & 116 & 198 & 494.4 &
65.3\% \\
Early start & 27.5 & 16 & 47.7 & 26 & 0 & 1262 & 83 & 225 & 587.7 &
34.7\% \\
\end{longtable}

The distribution of start-time deviations is centered close to zero, as
shown in Figure \ref{fig:start_diff_hist}, with a prominent peak around
small differences. This indicates that many surgeries begin near their
scheduled time. However, the histogram displays a clear right skew: late
starts occur more frequently and with a wider spread than early starts.
Most cases begin within roughly 30 minutes of plan, but the density
gradually tapers toward larger positive deviations, signalling that a
subset of surgeries experiences substantial delays. The long right-hand
tail highlights the presence of occasional extreme delays, which,
although rare, can disrupt downstream scheduling and reduce overall
operating room efficiency. On the left side, early starts also occur but
are less frequent and exhibit a shorter tail.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/start diff hist-1} 

}

\caption{Start time deviations (grouped per 10 minutes) \label{fig:start_diff_hist}}\label{fig:start diff hist}
\end{figure}

Average start-time delays vary moderately across the week, as shown in
Figure \ref{fig:start_delay_weekday}. During regular working days, mean
delays range from 11.1 minutes on Wednesday to 19.7 minutes on Friday.
Monday (19.2 minutes) and Tuesday (16.6 minutes) also show delays toward
the higher end of this range, while Thursday (13.4 minutes) remains
closer to the middle. These differences are modest, suggesting that
start-time punctuality is broadly consistent across weekdays, with no
evidence of systematic structural variation.

Weekend behavior differs slightly. Saturday shows a mean delay of 13.7
minutes, comparable to midweek levels, while Sunday displays the lowest
average delay of the entire week at 5.8 minutes. Lower weekend delays
likely reflect smaller surgical volumes and reduced scheduling pressure
rather than improved punctuality. Overall, the pattern indicates that
first-case delays are generally stable throughout the week, with only
mild fluctuations and no pronounced weekday--weekend divide.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/start delay weekday-1} 

}

\caption{Mean start delay by weekday \label{fig:start_delay_weekday}}\label{fig:start delay weekday}
\end{figure}

Late starts occur more frequently than early starts on every day of the
week, as shown in Table \ref{tab:start_diff_weekday}. Across regular
weekdays, approximately 64 to 67 percent of surgeries begin later than
scheduled. Mean delays range from 32.2 minutes on Wednesday to 43.7
minutes on Monday, while median delays fall between 20 and 29.5 minutes.
Early starts account for roughly 31 to 34 percent of cases, with mean
leads between --27 and --31 minutes and median leads around --17 to --19
minutes. These small differences across weekdays indicate broadly stable
punctuality, with no particular day exhibiting markedly better or worse
performance.

Weekend patterns show similar proportions but lower absolute timing
variation due to smaller case volumes. On Saturday and Sunday, late
starts comprise 61 to 63 percent of cases and are slightly below weekday
levels. The median delays drop to 7 minutes on Saturday and 3 minutes on
Sunday. Early starts remain around 30 to 31 percent, but mean leads
become somewhat larger in magnitude, reaching --37.3 minutes on Saturday
and --45.6 minutes on Sunday. These values reflect the different
operational context of weekend activity, where fewer scheduled cases and
a higher share of urgent procedures influence timing behavior. Overall,
weekday start-time performance is relatively consistent, while weekend
deviations reflect lower volumes and more irregular scheduling
conditions rather than systematic delay accumulation.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0917}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0734}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1651}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1193}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1376}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1743}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1101}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1284}}@{}}
\caption{Start-time deviation patterns per weekday (minutes).
\label{tab:start_diff_weekday}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Late starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Early starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean lead
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median lead
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Late starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Early starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean lead
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median lead
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Ma & 9932 & 66.2 & 43.7 & 28 & 31.8 & -30.5 & -18 \\
Di & 12308 & 63.8 & 41.4 & 27 & 33.8 & -28.9 & -18 \\
Wo & 9295 & 65.4 & 32.2 & 20 & 32.2 & -30.9 & -19 \\
Do & 11243 & 64.6 & 34.5 & 23 & 32.6 & -27.2 & -17 \\
Vr & 10503 & 67.1 & 43.3 & 29.5 & 30.8 & -30.5 & -18 \\
Za & 311 & 63.3 & 39.9 & 7 & 30.9 & -37.3 & -9.5 \\
Zo & 310 & 61 & 32.2 & 3 & 30.3 & -45.6 & -11 \\
\end{longtable}

Start-time reliability varies notably across operating rooms, as shown
in Table \ref{tab:start_diff_or}. The proportion of late starts ranges
from 46 percent in MKI3 to nearly 80 percent in MKI1 and MO02,
indicating that punctuality differs substantially between rooms. The
rooms with the highest rates of late starts are MKI1 (79.8 percent),
MO02 (79.6 percent), and MO03 (73 percent). These rooms also show
relatively large mean delays of 57.5 minutes, 34.7 minutes, and 55.3
minutes, respectively. This suggests more persistent difficulties in
beginning cases on time. Median delays in these rooms range from 23 to
51 minutes, which displays the pattern of recurrent lateness rather than
isolated extreme events.

Rooms such as MO04 (64.7 percent late starts), MO05 (63.3 percent), and
MO01 (62.3 percent) exhibit moderately high rates of late starts but
with more moderate mean delays around 35--37 minutes. These values
indicate consistent but less severe timing deviations. At the opposite
end of the spectrum, MKI3 stands out with only 46 percent late starts
and over half of its cases (52.3 percent) beginning early. Its mean
delay is 20.1 minutes, with a median delay of 15 minutes, making it the
most punctual room in the dataset.

The variation between rooms suggests that start-time deviations are not
uniformly distributed across the OR complex. Some operating rooms show
recurrent delays, while others demonstrate far more stable and
predictable timing performance. These differences may reflect
room-specific workflows, case compositions, staffing patterns, or
logistical constraints.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1000}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0727}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1636}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1182}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1364}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1727}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1091}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1273}}@{}}
\caption{Start-time deviation patterns per operating room (minutes).
\label{tab:start_diff_or}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Late starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Early starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean lead
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median lead
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Late starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median delay
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Early starts (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean lead
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median lead
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MKI1 & 8262 & 79.8 & 57.5 & 51 & 19.5 & -30.9 & -21 \\
MO02 & 8293 & 79.6 & 34.7 & 23 & 17.5 & -23.9 & -13 \\
MO03 & 4566 & 73 & 55.3 & 32 & 23.5 & -50.3 & -16 \\
MO06 & 4552 & 70.8 & 41.3 & 26 & 25.4 & -36.9 & -16 \\
MO04 & 5491 & 64.7 & 35 & 22 & 32.6 & -36.7 & -23 \\
MO05 & 4512 & 63.3 & 35.7 & 22 & 33.7 & -39.1 & -22 \\
MO01 & 4063 & 62.3 & 37 & 21 & 34.5 & -30.3 & -18 \\
MKI3 & 14163 & 46 & 20.1 & 15 & 52.3 & -22.5 & -17 \\
\end{longtable}

\subsection{Which procedures deviate most from
plan?}\label{which-procedures-deviate-most-from-plan}

Procedures vary substantially in how accurately their durations are
predicted, as shown in Table \ref{tab:duration_dev_proc}. The table
lists the twenty procedure types with the highest mean absolute
deviation between planned and observed operative time. Across these
procedures, average deviations range from approximately 28 to 65
minutes, indicating that for certain interventions, planning estimates
diverge considerably from realised durations.

The largest deviations occur in procedures such as DVC -- MK (mean
absolute deviation 64.8 minutes), TARUP (58.3 minutes), and EVENTRATIE
-- MK (55.4 minutes). These procedures tend to include complex surgical
steps or substantial intraoperative variability, which makes precise
planning more difficult. Several high-volume procedures, for example,
LAPAROTOMIE EXPLORATIE CHIR -- MK, LAPAROSCOPIE HEMICOLON RECHTS -- MK,
and TOTALE HEUPPROTHESE also show deviations above 40 minutes,
demonstrating that unpredictability persists even for interventions
performed frequently.

Across most of the listed procedures, longer-than-planned cases are
slightly more common than shorter ones. For instance, procedures such as
LAPAROSCOPIE HEMICOLON RECHTS -- MK show 82.6 percent of cases finishing
later than planned, while others such as PERCUTANE NEFROLITHOTRAPAXIE --
MK show the opposite pattern, with 71.9 percent finishing earlier. These
contrasts underline that deviation patterns depend not only on the
procedure type but also on inherent clinical uncertainty and variation
in patient presentation.

Overall, the results confirm that planning accuracy is strongly
procedure-dependent. Routine operations with standardized workflows tend
to show smaller deviations, while complex, technically demanding, or
less frequently performed procedures exhibit substantially greater
uncertainty in their operative times.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2640}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0480}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1680}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1040}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1520}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1120}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1520}}@{}}
\caption{Top 20 procedures by average absolute duration deviation
(Maaseik). \label{tab:duration_dev_proc}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean abs dev (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Longer (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean + dev (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Shorter (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean - dev (min)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean abs dev (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Longer (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean + dev (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Shorter (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean - dev (min)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
DVC - MK & 34 & 64.8 & 35.3 & 57.8 & 64.7 & -68.6 \\
TARUP EVENTRATIE - MK & 45 & 58.3 & 53.3 & 62.7 & 46.7 & -53.3 \\
LAPAROTOMIE EXPLORATIE CHIR - MK & 81 & 55.4 & 60.5 & 67.8 & 39.5 &
-36.3 \\
LAPAROSCOPIE HEMICOLON RECHTS - MK & 46 & 45.8 & 82.6 & 52.6 & 15.2 &
-15.1 \\
TOTALE HEUPPROTHESE DAA REVISIE - MK & 47 & 44.1 & 59.6 & 57 & 38.3 &
-26.4 \\
HEUP ARTHROSCOPIE - MK & 62 & 44 & 40.3 & 48.6 & 59.7 & -40.9 \\
TOTALE KNIEPROTHESE REVISIE - MK & 31 & 43.4 & 61.3 & 44.3 & 38.7 &
-41.9 \\
LAPAROSCOPIE COLON PME - MK & 114 & 41 & 64 & 52.5 & 36 & -20.5 \\
LAPAROSCOPIE EXPLORATIE CHIR - MK & 190 & 39.7 & 54.2 & 46.4 & 43.7 &
-33.3 \\
PERCUTANE NEFROLITHOLAPAXIE - MK & 32 & 34.3 & 28.1 & 19 & 71.9 &
-40.3 \\
ENKEL FRAKTUUR AO KLEIN FRAGMENT & 34 & 34 & 55.9 & 33.9 & 44.1 & -34 \\
LAPAROTOMIE EVENTRATIE - MK & 47 & 32.7 & 31.9 & 46.5 & 63.8 & -28 \\
TOTALE HEUPPROTHESE DAA BILATERAAL - MK & 38 & 31.5 & 44.7 & 39.2 & 52.6
& -26.5 \\
POLSFRACTUUR PLAAT+SCHROEVEN - MK & 184 & 31.2 & 66.8 & 37 & 32.6 &
-19.9 \\
TYMPANOPLASTIE + MASTOÏDECTOMIE - MK & 74 & 31.1 & 58.1 & 37.4 & 41.9 &
-22.4 \\
ENKELFRACTUUR PLAAT+SCHROEVEN - MK & 151 & 30.3 & 58.3 & 35.1 & 41.1 &
-24 \\
VOS TIBIA - MK & 44 & 29.2 & 36.4 & 22.4 & 61.4 & -34.3 \\
TYMPANOPLASTIE MET VRIJMAKEN DER VENSTERS - MK & 61 & 28.2 & 60.7 & 25.6
& 39.3 & -32.1 \\
VARICES VSM - MK & 61 & 28.2 & 49.2 & 28.6 & 50.8 & -27.8 \\
VARICES LASER BILATERAAL - MK & 53 & 28.1 & 75.5 & 31.5 & 24.5 &
-17.7 \\
\end{longtable}

The scatter plot in Figure \ref{fig:volume_deviation} shows an inverse
relationship between procedure volume and average deviation. Procedures
that occur more frequently tend to have lower mean absolute deviations,
while rare procedures show much greater variability in duration. This
pattern is visible in the downward trend of the points as procedure
volume increases.

High-volume procedures, which appear toward the right of the chart,
cluster at lower deviation values, indicating more stable and
predictable planning performance. In contrast, low-volume procedures on
the left display a much wider range of deviations that can exceed 60
minutes. The relationship suggests that familiarity and repetition
contribute to more accurate duration estimates, whereas infrequent
procedures are harder to predict due to limited historical data.
Overall, the figure highlights that case volume is an important factor
in explaining the variability of planning accuracy across procedure
types.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/volume_deviation-1} 

}

\caption{Relationship between procedure volume and mean deviation \label{fig:volume_deviation}}\label{fig:volume_deviation}
\end{figure}

The distribution of duration deviations across surgeons reveals notable
variation in planning accuracy, as shown in Table
\ref{tab:surgeon_deviation}. Among those with at least fifty recorded
procedures, the average absolute deviation ranges from 30.4 to 68.1
minutes, while the average relative deviation spans 17.2\% to 52.6\%. A
few surgeons show comparatively high mean deviations above 55 minutes,
whereas most fall between 30 and 40 minutes, indicating that planning
performance differs across individuals but remains within a moderate
range for the majority.

No clear relationship appears between the number of recorded cases and
the size of the deviation, suggesting that factors beyond case volume
influence the observed variation. Overall, the results show that
duration deviations are not uniformly distributed across surgeons,
emphasizing that planning accuracy can vary meaningfully even within a
shared operational environment.

\begin{longtable}[]{@{}lccc@{}}
\caption{Top 15 surgeons by average absolute and relative duration
deviation (pseudonymized). \label{tab:surgeon_deviation}}\tabularnewline
\toprule\noalign{}
Surgeon & n & Mean absolute dev (min) & Mean relative dev (\%) \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Surgeon & n & Mean absolute dev (min) & Mean relative dev (\%) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Surgeon 1 & 66 & 38.9 & 31.5 \\
Surgeon 2 & 85 & 35.0 & 42.4 \\
Surgeon 3 & 260 & 26.7 & 32.6 \\
Surgeon 4 & 71 & 26.3 & 36.0 \\
Surgeon 5 & 393 & 26.0 & 38.6 \\
Surgeon 6 & 449 & 23.0 & 30.9 \\
Surgeon 7 & 2785 & 22.6 & 36.0 \\
Surgeon 8 & 343 & 22.2 & 25.2 \\
Surgeon 9 & 153 & 21.5 & 37.5 \\
Surgeon 10 & 870 & 19.5 & 21.7 \\
Surgeon 11 & 1944 & 19.3 & 27.7 \\
Surgeon 12 & 100 & 18.7 & 86.0 \\
Surgeon 13 & 93 & 18.7 & 24.4 \\
Surgeon 14 & 1847 & 18.5 & 26.2 \\
Surgeon 15 & 110 & 18.1 & 152.8 \\
\end{longtable}

\newpage

\section{Do surgeries stay within regular working
hours?}\label{do-surgeries-stay-within-regular-working-hours}

\subsection{How often do cases extend beyond their assigned time
window?}\label{how-often-do-cases-extend-beyond-their-assigned-time-window}

Around 2.8 percent of all surgeries at Maaseik continue beyond the
scheduled shift end of the operating team, as shown in Table
\ref{tab:overtime_summary}. On average, these extended cases run about
42 minutes beyond the planned shift, with a median of 29 minutes. Most
overruns are therefore relatively short, though a smaller subset lasts
considerably longer, as reflected in the 95th percentile of 129 minutes.
These outliers typically involve complex or unpredictable procedures
that cannot be concluded within the planned block.

The results indicate that overtime is a recurring feature across the
full 24-hour cycle. Although the large majority of surgeries conclude
within their scheduled working periods, the 2.8 percent share of
extended cases points to regular spillover between adjacent shifts. The
substantial spread in overtime duration also shows that while most
overruns are moderate, a small number of prolonged sessions contribute
disproportionately to the evening and night workload.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2708}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1354}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1875}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1562}}@{}}
\caption{Overall share and duration of after-hours surgeries (Maaseik).
\label{tab:overtime_summary}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Surgeries with overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95 Overtime
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Surgeries with overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95 Overtime
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
53902 & 1494 & 2.8 & 42 & 29 & 129 \\
\end{longtable}

he distribution of overtime duration, shown in Figure
\ref{fig:overtime_dist}, is strongly right-skewed. Most extended cases
finish within the first 60 minutes beyond the scheduled shift, with the
highest concentration in the 10--20-minute range. Beyond this point,
frequencies decline steadily, and only a small fraction of cases exceed
200 minutes. A few rare outliers extend beyond 300 minutes, but these
represent exceptional circumstances rather than routine deviations.

This pattern confirms that while overtime is a recurring operational
feature, it is typically limited in duration. The long right tail
illustrates that a small number of prolonged procedures account for a
disproportionate share of total overtime minutes. Although these
outliers can significantly affect staff workload and room turnover late
in the day, they do not represent the typical case. Overall, overtime at
Maaseik mainly consists of brief extensions of planned activity rather
than frequent or sustained night-time operating.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_dist-1} 

}

\caption{Distribution of overtime duration for after-hours surgeries \label{fig:overtime_dist}}\label{fig:overtime_dist}
\end{figure}

The share of surgeries extending beyond scheduled shift hours remains
low and relatively stable throughout the regular workweek, as shown in
Figure \ref{fig:afterhours_weekday}. From Monday to Thursday,
after-hours cases account for only 2.2 to 2.7 percent of all surgeries,
increasing slightly to 3.5 percent on Friday. These small and steady
values indicate that weekday operations at Maaseik are generally well
contained within their planned timeframes, with only a limited fraction
of cases requiring additional time beyond the scheduled shift.

A clearer rise occurs during the weekend. On Saturday, 4.5 percent of
surgeries extend beyond shift boundaries, and on Sunday this share
increases sharply to 8.7 percent, the highest of the week. Although
weekend case volumes are lower, these proportions show that a
substantially larger share of procedures performed on weekends exceed
the available shift window. This likely reflects the higher prevalence
of urgent or semi-urgent interventions during weekends, which are less
predictable in both timing and duration.

Overall, the weekday--weekend contrast highlights how overtime at
Maaseik is structurally embedded in the hospital's continuous surgical
service. While overtime during weekdays is relatively infrequent and
well controlled, weekend operations more often extend into subsequent
shifts due to the emergency-driven case mix.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/afterhours_weekday-1} 

}

\caption{Share of after-hours surgeries by weekday \label{fig:afterhours_weekday}}\label{fig:afterhours_weekday}
\end{figure}

The proportion of surgeries extending beyond scheduled shift hours has
remained low and broadly stable over time, as illustrated in Figure
\ref{fig:afterhours_trend}. In 2022, about 2.7 percent of all surgeries
at Maaseik exceeded their scheduled shift, increasing slightly to 2.8
percent in both 2023 and 2024, before declining to 2.6 percent in the
partial dataset for 2025.

These values represent the percentage of procedures in each year that
continued past the official end of their assigned shift. The small
year-to-year movements suggest that the frequency of after-hours cases
has remained steady, with a mild reduction visible in the most recent
year.

Although the changes are modest, the pattern indicates stable adherence
to scheduled shift boundaries and suggests that daytime throughput and
list planning processes are functioning consistently across years.
Overall, overtime remains a relatively small but persistent component of
operating room activity at Maaseik, with little indication of structural
increase or deterioration over time.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/afterhours_trend-1} 

}

\caption{Evolution of after-hours activity over time \label{fig:afterhours_trend}}\label{fig:afterhours_trend}
\end{figure}

The proportion of surgeries extending beyond scheduled shift hours
differs markedly across operating rooms, as summarized in Table
\ref{tab:overtime_or}. Most rooms show overtime rates between 4 and 9
percent, while a few stand out with substantially lower shares. MO03
records the highest proportion of overtime cases at 8.9 percent, with a
mean duration of 62.2 minutes and a 95th percentile of 180.8 minutes,
indicating frequent and occasionally prolonged extensions. Such figures
likely reflect the type of procedures performed in this room, which may
be more complex or less predictable in length.

Several other rooms, including MO05, MO04, and MO06, show overtime in
roughly 5 to 6 percent of cases, with mean durations between 36.2 and 42
minutes. These values suggest that while most surgeries in these rooms
finish within their allocated shift, a notable share still extends into
the next operational block.

In contrast, rooms such as MO01 and MO02 show more moderate overtime
frequencies below 5 percent, with average extensions typically between
14.5 and 34.4 minutes. The lowest rates occur in the MKI1 and MKI3
rooms, where overtime is rare and mean durations remain short.

Overall, the data indicate that overtime at Maaseik is concentrated in a
limited number of operating rooms with heavier or more variable case
mixes. While many rooms complete their scheduled activity within the
planned shift most of the time, a subset still experiences overtime in 5
to 9 percent of surgeries, showing that after-shift extensions remain a
recurring part of daily operations rather than isolated exceptions.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1279}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0930}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2907}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1860}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2093}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0930}}@{}}
\caption{Operating rooms by after-hours activity (Maaseik).
\label{tab:overtime_or}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Cases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage of overtime surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Cases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage of overtime surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO03 & 4566 & 8.9 & 62.2 & 44 & 180.8 \\
MO05 & 4512 & 6 & 36.2 & 27.5 & 93.7 \\
MO04 & 5491 & 5.1 & 42 & 35 & 105.1 \\
MO06 & 4552 & 4.7 & 36.8 & 31 & 106.6 \\
MO01 & 4063 & 4.2 & 34.4 & 26 & 106.5 \\
MO02 & 8293 & 1.1 & 14.5 & 9 & 32 \\
MKI3 & 14163 & 0.3 & 13.3 & 12 & 33.6 \\
MKI1 & 8262 & 0.2 & 18.4 & 6 & 57 \\
\end{longtable}

\subsection{When does overtime occur, and how heavy is
it?}\label{when-does-overtime-occur-and-how-heavy-is-it}

The distribution of overtime surgeries, shown in Figure
\ref{fig:overtime_timing}, displays a clear concentration of cases
ending in the first one to two hours after the regular shift boundary at
16:30. The largest peak occurs around 17:00, followed by substantial
numbers of cases finishing near 17:30 and 18:00. These observations
primarily reflect procedures that began during the daytime schedule but
required additional time to complete.

As the evening progresses, the number of overtime surgeries declines
sharply. Only a small number of cases finish after 20:00, and a distinct
but limited secondary cluster appears around 23:00. Operations ending
during the late evening or night are therefore relatively infrequent.
Very few procedures extend past midnight, and only isolated cases finish
between 03:00 and 07:00.

Overall, the pattern demonstrates that overtime activity is dominated by
surgeries that conclude soon after the end of the regular working day,
while operations finishing late at night contribute only a small share
of total overtime. Most after-hours activity represents brief extensions
of daytime work rather than sustained night-time operating.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_timing-1} 

}

\caption{Timing of overtime surgeries \label{fig:overtime_timing}}\label{fig:overtime_timing}
\end{figure}

Average overtime durations show moderate variation across weekdays, as
illustrated in Figure \ref{fig:overtime_weekday}. Mean values range from
31.7 minutes on Thursday to 48.1 minutes on Tuesday, while Monday,
Wednesday, and Friday all fall between 39.9 and 44.6 minutes. Median
durations are consistently lower than the means, varying from 23 to 33.5
minutes, indicating a right-skewed distribution in which a small number
of long overruns raise the average beyond the typical case.

A similar pattern appears on the weekend. Saturday shows the highest
mean overtime duration at 52.9 minutes, alongside a median of 45.5
minutes, while Sunday records a mean of 44.8 minutes and a median of 40
minutes. These values should not be interpreted as shorter or longer
relative to daytime hours; rather, they reflect the overtime profile of
cases that extend beyond their scheduled shift, independent of weekday
or weekend scheduling structures.

Overall, once surgeries run past the shift boundary, the typical overrun
ranges from about 25 to 45 minutes, as reflected in the median values,
while the means cluster closer to 40 to 50 minutes because of a limited
number of prolonged extensions. This pattern highlights that most
overtime cases represent modest delays, with only a small subset
contributing disproportionately to average overtime duration.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_weekday-1} 

}

\caption{Average and median overtime duration by weekday \label{fig:overtime_weekday}}\label{fig:overtime_weekday}
\end{figure}

Average and median overtime durations per surgery show a stable pattern
over the observed years, as illustrated in Figure
\ref{fig:overtime_year}. The mean varies only slightly, from 43 minutes
in 2022 to 42.6 minutes in 2023, 43.2 minutes in 2024, and a slightly
lower 35.9 minutes in 2025. The median consistently remains below the
mean, ranging from 25 to 31 minutes across the same period.

This persistent gap between the mean and median indicates that overtime
durations are right-skewed, with a minority of lengthy overruns pulling
the mean upward. In most years, the typical overtime duration (median)
is therefore around 25 to 31 minutes, while the average sits closer to
40 minutes, reflecting the influence of occasional long cases.

The small year-to-year changes suggest that the overall duration of
overtime has remained stable. At the same time, the difference between
mean and median values shows that the underlying distribution is not
uniform: years with similar averages can still exhibit very different
spreads. This pattern highlights that a limited number of extended
overruns continues to account for a disproportionate share of total
overtime minutes.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_year-1} 

}

\caption{Average and median overtime per surgery by year \label{fig:overtime_year}}\label{fig:overtime_year}
\end{figure}

The distribution of overtime differs noticeably between shift types, as
shown in Figure \ref{fig:overtime_shift}. The day shift (08:00--16:30)
displays the widest spread, with most cases extending only slightly
beyond the scheduled end but a small number continuing for several
hours. This broad distribution reflects the higher case volume and
greater procedural variability during daytime hours, which explains why
the day shift accounts for the majority of total overtime minutes.

In the evening shift (16:30--22:00), the spread is narrower and most
cases cluster close to zero, indicating that only a limited share of
procedures extends far beyond the planned shift end. Although a few
longer overruns appear, they are markedly less frequent than during the
day.

The night shift (22:00--08:00) shows a similar pattern, with most
observations concentrated around short extensions and only a few long
outliers. The much lower density of points reflects the small number of
surgeries performed during this period, making extended overtime events
relatively rare.

Overall, the distributions illustrate that overtime is most variable
during the day, when activity levels and case complexity are highest,
and becomes progressively more contained during the later shifts. The
pronounced right tails in each group confirm that a limited number of
long-running procedures account for a substantial share of total
overtime minutes.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_shift-1} 

}

\caption{Relative overtime per shift type \label{fig:overtime_shift}}\label{fig:overtime_shift}
\end{figure}

\subsection{How does Maaseik compare with Cathlab, Lanaken, and
Genk?}\label{how-does-maaseik-compare-with-cathlab-lanaken-and-genk}

The comparison between campuses highlights clear differences in
after-hours activity, with Maaseik occupying an intermediate position
within this pattern. At Maaseik, 2.8 percent of all surgeries extend
beyond the scheduled shift boundary, substantially lower than Genk (8.4
percent) and Cathlab (5.8 percent) but higher than at Lanaken (0.5
percent). This reflects Maaseik's focused surgical profile: the campus
handles a substantial volume of planned interventions but performs fewer
highly complex procedures that typically run long.

Overtime durations at Maaseik fall between those of the other sites. The
average overrun is 42 minutes, with a median of 29 minutes and a 95th
percentile of 129 minutes. These values show that extended cases occur
regularly but remain contained, unlike Genk, where mean overtime reaches
59 minutes and the upper tail extends beyond 193 minutes. Compared with
Lanaken, Maaseik experiences both longer and more frequent overruns,
since Lanaken's limited after-hours activity produces much shorter
median and tail durations.

Taken together, the results show that Maaseik experiences a moderate
level of after-hours surgical work, more than the smaller Lanaken campus
but considerably less than Genk. The Cathlab also exhibits a controlled
but non-negligible share of overtime. Overall, this places Maaseik in a
balanced position within the ZOL network, where occasional overruns
occur but extended evening work is not a dominant feature of daily
operations.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0820}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0656}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1803}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2459}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1557}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1475}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1230}}@{}}
\caption{Comparison of after-hours activity between campuses.
\label{tab:afterhours_campus}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Campus
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
AfterHour surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Share of overtime surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Average Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95 Overtime
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Campus
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
AfterHour surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Share of overtime surgeries
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Average Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median Overtime
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95 Overtime
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Genk & 96044 & 8024 & 8.4 & 59 & 38 & 193.8 \\
Cathlab & 9282 & 539 & 5.8 & 41.8 & 32 & 108.3 \\
Maaseik & 53902 & 1494 & 2.8 & 42 & 29 & 129 \\
Lanaken & 69395 & 371 & 0.5 & 15.7 & 10 & 48.5 \\
\end{longtable}

\newpage

\section{Are surgeries performed in their assigned operating
rooms?}\label{are-surgeries-performed-in-their-assigned-operating-rooms}

\subsection{How frequently are surgeries relocated to a different
room?}\label{how-frequently-are-surgeries-relocated-to-a-different-room}

Room reallocations at Maaseik are rare, as shown in Table
\ref{tab:room_swap}. Out of 53902 recorded surgeries, only 413 cases
were performed in a different operating room than originally planned,
corresponding to 0.8 percent of all procedures. This proportion is
slightly lower than the rate observed at Genk and higher than the near
zero values at Lanaken, indicating that room assignments at Maaseik are
generally stable and require only limited reactive adjustments during
daily operations.

Although infrequent, these relocations matter operationally because they
typically arise from last minute scheduling constraints, such as
unexpected overruns, equipment availability, or staff distribution
across rooms. Even small shifts of this kind can influence preparation
workflows, turnover sequencing, and coordination between surgical teams.
Monitoring their frequency therefore provides insight into how resilient
the planning process is and whether disruptions tend to be isolated
events or concentrated in specific rooms or time periods.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2917}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1944}}@{}}
\caption{Overall frequency of surgeries relocated to a different room
(Maaseik). \label{tab:room_swap}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Swapped (absolute)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Swapped (\%)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Swapped (absolute)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Swapped (\%)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
53902 & 413 & 0.8 \\
\end{longtable}

The share of relocated surgeries remains very low across all weekdays,
as shown in Figure \ref{fig:room_swap_weekday}, fluctuating between 0.5
and 1.3 percent. This narrow range indicates that room assignments are
highly stable during regular working days, with only limited need for
reactive changes. Monday shows the lowest proportion of relocations,
while Wednesday and Friday exhibit slightly higher values, though still
close to one percent.

A noticeable increase occurs during the weekend, where the share rises
to 4.8 percent on Saturday and 3.5 percent on Sunday. These elevated
rates likely reflect the reduced number of available rooms and the more
variable case mix characteristic of weekend operations, which can make
adherence to planned room allocations more difficult.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/room_swap_weekday-1} 

}

\caption{Share of relocated surgeries by weekday \label{fig:room_swap_weekday}}\label{fig:room_swap_weekday}
\end{figure}

The monthly percentage of surgeries that are relocated to a different
operating room fluctuates between 0.5 and 2 percent, as shown in Figure
\ref{fig:room_swap_month}. Despite noticeable month-to-month variation,
there is no clear upward or downward trend across the observed period.
Occasional peaks above 1.5 percent indicate that some months experience
more frequent reallocations, yet these occur as isolated spikes rather
than forming any sustained pattern.

The consistently low baseline shows that room swaps remain rare and are
typically driven by temporary scheduling pressures or logistical
constraints. The absence of a systematic trend over time suggests that
the stability of room assignments at Maaseik has remained largely
unchanged throughout the study period.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/room_swap_month-1} 

}

\caption{Monthly percentage of surgeries with room swap \label{fig:room_swap_month}}\label{fig:room_swap_month}
\end{figure}

\subsection{Are specific rooms affected more than
others?}\label{are-specific-rooms-affected-more-than-others}

The analysis shows that only a limited number of operating rooms are
regularly involved in relocations, as summarized in Table
\ref{tab:room_swap_or}. A small subset of rooms acts as central nodes
that receive or exchange cases more frequently, while most other rooms
are affected only occasionally. In the main operating block, MO04 and
MO05 form the most prominent pair: they exchange cases frequently and
appear to function as mutual overflow buffers when one room runs short
on capacity. Similar patterns appear between MO03 and MO06, which also
show repeated bidirectional swaps.

These consistent interactions indicate that room reallocations follow
operational logic rather than occurring at random. Rooms with comparable
setups, adjacent locations, or overlapping specialty coverage tend to
exchange cases when small scheduling conflicts arise. Rather than
signaling instability, these movements reflect the adaptive use of
available capacity to maintain continuity in the surgical program when
plans need minor adjustments.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1017}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1102}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1610}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1610}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1610}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1525}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1525}}@{}}
\caption{Top 10 planned ORs with the highest number of room swaps,
showing the five most frequent new OR destinations (Maaseik).
\label{tab:room_swap_or}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
PlannedOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
TotalMoved
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top5
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
PlannedOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
TotalMoved
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Top5
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO04 & 132 & MO05 (93, 70.5\%) & MO03 (22, 16.7\%) & MO06 (8, 6.1\%) &
MO01 (5, 3.8\%) & MO02 (3, 2.3\%) \\
MO05 & 92 & MO04 (42, 45.7\%) & MO06 (22, 23.9\%) & MO03 (17, 18.5\%) &
MO01 (9, 9.8\%) & MKI1 (1, 1.1\%) \\
MO03 & 64 & MO06 (24, 37.5\%) & MO04 (15, 23.4\%) & MO05 (14, 21.9\%) &
MO01 (7, 10.9\%) & MKI1 (2, 3.1\%) \\
MO06 & 49 & MO05 (18, 36.7\%) & MO03 (15, 30.6\%) & MO04 (7, 14.3\%) &
MO01 (6, 12.2\%) & MKI1 (2, 4.1\%) \\
MO01 & 30 & MO03 (10, 33.3\%) & MO06 (8, 26.7\%) & MO05 (5, 16.7\%) &
MO02 (4, 13.3\%) & MKI1 (1, 3.3\%) \\
MO02 & 25 & MO06 (10, 40\%) & MO01 (9, 36\%) & MO03 (2, 8\%) & MO04 (2,
8\%) & MO05 (2, 8\%) \\
GO01 & 3 & MO05 (2, 66.7\%) & MO01 (1, 33.3\%) & NA & NA & NA \\
GOR0 & 2 & MO02 (1, 50\%) & MO05 (1, 50\%) & NA & NA & NA \\
MKI1 & 1 & MO05 (1, 100\%) & NA & NA & NA & NA \\
MKI3 & 1 & MO06 (1, 100\%) & NA & NA & NA & NA \\
\end{longtable}

A small number of operating rooms receive the majority of relocated
surgeries, as shown in Table \ref{tab:room_swap_dest}. The clearest
destination is MO05, which alone receives 136 transferred cases,
representing one quarter of all relocations. Other rooms with similarly
prominent roles include MO06, MO03, and MO04, each absorbing between 68
and 76 relocated procedures. These rooms function as the principal
buffers in the system, taking on cases when adjustments to the planned
schedule become necessary.

The distribution is highly concentrated: only a handful of rooms receive
the overwhelming majority of relocations, while the remaining ORs are
involved only sporadically. For example, rooms such as MO01 and MO02
receive far fewer transferred cases, and several rooms register only a
small number of relocations. This concentration suggests that certain
operating rooms are more adaptable, either because they have broader
procedural compatibility, more flexible staffing, or more consistent
availability to absorb unplanned activity.

Overall, although relocations remain rare in absolute terms, the pattern
shows that when adjustments occur, they are directed primarily toward a
small set of rooms that serve as the operational safety net for managing
day-to-day variability.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2222}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1528}}@{}}
\caption{Top 15 actual operating rooms most frequently used as
destinations after relocation (Maaseik).
\label{tab:room_swap_dest}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ReceivedCases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ReceivedCases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO05 & 136 & 0.25 \\
MO06 & 76 & 0.14 \\
MO03 & 68 & 0.13 \\
MO04 & 68 & 0.13 \\
MO01 & 42 & 0.08 \\
MO02 & 15 & 0.03 \\
MKI1 & 7 & 0.01 \\
MKI3 & 1 & 0 \\
\end{longtable}

Procedures with the highest likelihood of being relocated mainly consist
of short, standardized interventions, as shown in Table
\ref{tab:room_swap_procedure}. At the top of the list are procedures
such as DVC -- MK, cardioversion, abscess drainage, and several minor
orthopedic or trauma-related interventions, all of which show relocation
rates far above the campus baseline of 0.8 percent. The highest values
exceed 20 percent, indicating that these procedures are particularly
flexible in terms of room assignment.

The pattern suggests that relocations most often involve short,
low-complexity procedures that can be performed in multiple suitable
rooms without requiring specialized infrastructure. This flexibility
makes them easier to reassign when schedule adjustments are needed. In
contrast, longer inpatient procedures or interventions requiring
specialized equipment appear far less frequently among the relocated
cases.

Overall, the table shows that room swaps at Maaseik are concentrated in
a narrow group of routine, easily transferable procedures, reflecting an
operational strategy in which schedulers preferentially reassign cases
that create minimal disruption to the broader OR program.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4583}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1389}}@{}}
\caption{Top 15 procedure types with the highest share of relocated
surgeries (Maaseik). \label{tab:room_swap_procedure}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SwapPct
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ProcedureName
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SwapPct
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
DVC - MK & 34 & 24.24 \\
CARDIOVERSIE STANDAARD - MK & 133 & 22.73 \\
CARDIOVERSIE NA TEE - MK & 93 & 19.35 \\
ABCESDRAINAGE & 39 & 12.82 \\
HEUP / TOTALE HEUPPROTHESE & 33 & 12.5 \\
PEESHECHTING - MK & 30 & 10 \\
ACHILLESPEESHECHTING - MK & 35 & 8.57 \\
PINNING HAND - MK & 49 & 6.38 \\
SCHOUDERLUXATIE REPOSITIE - MK & 32 & 6.25 \\
POLSFRACTUUR PLAAT+SCHROEVEN - MK & 184 & 5.98 \\
ANALE FISTEL - MK & 35 & 5.71 \\
ENKELFRACTUUR PLAAT+SCHROEVEN - MK & 151 & 5.3 \\
FESS UNILAT - MK & 47 & 4.26 \\
POLS FRAKTUUR DISTAAL RADIUS & 47 & 4.26 \\
VOS ENKEL - MK & 71 & 4.23 \\
\end{longtable}

\subsection{What is the operational impact of these
reallocations?}\label{what-is-the-operational-impact-of-these-reallocations}

Relocated surgeries differ from non-relocated ones in several aspects of
timing and scheduling performance, as summarized in Table
\ref{tab:room_swap_impact}. For start times, relocated cases show
markedly larger deviations in both directions. Among late starts, the
average delay is 73.9 minutes for relocated cases compared with 38.8
minutes for non-relocated ones. Early starts show a similar pattern:
relocated surgeries begin on average 81 minutes before schedule, versus
29.2 minutes for non-relocated surgeries. These differences indicate
that relocated cases are more likely to be scheduled under time pressure
or atypical circumstances that push them further from their planned
start times. Median values are somewhat closer together (49 vs 25
minutes for late starts, 56 vs 18 minutes for early starts), but still
reflect greater variability around the intended schedule.

For procedure duration, both groups diverge from their planned times,
but relocated surgeries show systematically larger deviations.
Longer-than-planned cases average 25.4 minutes of overrun for relocated
surgeries compared with 13.8 minutes for non-relocated ones.
Shorter-than-planned cases show a similar gap: 16.8 minutes for
relocated surgeries versus 9.7 minutes for non-relocated ones. This
suggests that, while relocation does not necessarily change the
intrinsic length of procedures, it is associated with conditions that
amplify timing uncertainty.

Despite these differences, overtime remains limited in both groups.
Median overtime is zero for relocated and non-relocated cases, and the
mean is only slightly higher for relocated surgeries (4.7 vs 1.1
minutes). This indicates that relocations rarely push procedures far
enough into the next shift to create sustained after-hours activity.

Overall, the results show that relocations are primarily linked to
greater variability in start times and duration deviations, rather than
systematically longer surgeries or extended overtime. Their operational
impact therefore appears to stem from scheduling constraints and
coordination challenges rather than from the procedures themselves.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2222}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2639}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0972}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1250}}@{}}
\caption{Comparison of start and duration deviations (early/late,
shorter/longer) and overtime between relocated and non-relocated
surgeries (Maaseik). \label{tab:room_swap_impact}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Metric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Metric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Relocated & Late start & 73.9 & 49 \\
Not relocated & Late start & 38.8 & 25 \\
& ---- & & \\
Relocated & Early start & 81 & 56 \\
Not relocated & Early start & 29.2 & 18 \\
& ---- & & \\
Relocated & Longer duration & 25.4 & 18 \\
Not relocated & Longer duration & 13.8 & 8 \\
& ---- & & \\
Relocated & Shorter duration & 16.8 & 11 \\
Not relocated & Shorter duration & 9.7 & 6 \\
& ---- & & \\
Relocated & Overtime & 4.7 & 0 \\
Not relocated & Overtime & 1.1 & 0 \\
& ---- & & \\
\end{longtable}

Overtime is more common among relocated surgeries than among those
performed in their originally assigned room, as shown in Table
\ref{tab:overtime_relocation}. About 2.7 percent of non-relocated
surgeries extend beyond 16:30, compared with 10.7 percent of relocated
surgeries. This difference suggests that relocated cases are more likely
to occur under time-pressured or unscheduled circumstances, such as
late-day adjustments or capacity constraints, which can increase the
likelihood of after-hours completion.

Even so, the overall numbers remain small, and the vast majority of
surgeries---relocated or not---finish within their planned operating
window. The results indicate that room reassignments, while
operationally meaningful, are not a major driver of evening work at the
campus level. Relocations require coordination but do not substantially
increase the after-hours workload.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2222}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4306}}@{}}
\caption{Share of after-hours surgeries by relocation status (Maaseik).
\label{tab:overtime_relocation}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
SwapGroup
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
AfterHours
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage of surgeries with afterhours
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
SwapGroup
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
AfterHours
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage of surgeries with afterhours
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Not relocated & 1444 & 2.7 \\
Relocated & 44 & 10.7 \\
\end{longtable}

The distribution of overtime duration for relocated surgeries, shown in
Figure \ref{fig:overtime_relocated}, is heavily concentrated near zero,
indicating that most relocated cases finish within regular working hours
or only slightly beyond them. The histogram shows a steep decline after
the first 20--30 minutes of overtime, and only a small number of
relocated surgeries extend past one hour. A few isolated cases reach 100
minutes or more, but these remain rare and form a long, sparse right
tail.

This pattern reinforces the earlier finding that relocations typically
involve short or moderately timed procedures that can be completed
quickly once moved to another room. The limited overtime associated with
these cases suggests that room reassignments are handled efficiently and
generally do not lead to extended evening activity. Operationally,
relocated surgeries function as flexible adjustments to manage workload
or scheduling conflicts rather than as sources of prolonged delays.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overtime_relocated-1} 

}

\caption{Distribution of overtime duration for relocated surgeries \label{fig:overtime_relocated}}\label{fig:overtime_relocated}
\end{figure}

\newpage

\section{How do urgent cases disrupt elective
planning?}\label{how-do-urgent-cases-disrupt-elective-planning}

\subsection{When and where do urgent surgeries
occur?}\label{when-and-where-do-urgent-surgeries-occur}

The majority of surgeries at Maaseik are elective, representing 94.3
percent of all recorded cases, as shown in Table \ref{tab:urgency_dist}.
Non elective or urgent surgeries account for the remaining 5.7 percent.
Although this is a relatively small share, it still reflects a steady
stream of unscheduled or time sensitive cases that enter the daily
workflow.

The presence of this non elective segment is operationally important.
Even a small proportion of urgent cases can influence the stability of
daily planning because their timing is unpredictable and they must be
accommodated immediately or within a narrow clinical window.
Understanding when and where these unplanned procedures occur provides
essential context for evaluating their interaction with elective
activity and assessing whether they contribute to schedule deviations,
room pressure, or after hours work.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2222}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1528}}@{}}
\caption{Distribution of surgeries by urgency classification (Maaseik).
\label{tab:urgency_dist}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
UrgencyType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
UrgencyType
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
electief & 50811 & 94.3 \\
niet-electief & 3091 & 5.7 \\
\end{longtable}

The start times of non elective surgeries, shown in Figure
\ref{fig:urgency_timing}, display a clear concentration during daytime
hours, with a pronounced peak between 13:00 and 15:00. This pattern
indicates that most urgent procedures occur within or close to regular
operating hours, where they overlap with ongoing elective activity and
place additional pressure on room availability. A smaller but persistent
level of activity extends into the evening, reflecting cases that emerge
later in the day and require timely intervention.

Night time activity is limited, with very few non elective surgeries
beginning between midnight and early morning. Overall, the distribution
shows that non elective cases are not evenly spread across the 24 hour
period. Instead, they cluster strongly in the afternoon and early
evening, precisely when operating room capacity is already heavily
used---highlighting their potential to disrupt scheduling and increase
operational strain.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/urgency_timing-1} 

}

\caption{Daily distribution of non-elective surgery start times \label{fig:urgency_timing}}\label{fig:urgency_timing}
\end{figure}

Across all weekdays, non elective surgeries follow a consistent hourly
pattern, as illustrated in Figure \ref{fig:urgency_weekday}. Most
activity occurs between late morning and early evening, with pronounced
peaks around 13:00 to 15:00 on nearly every weekday. This confirms that
urgent procedures are frequently performed during regular daytime hours.
Because these peaks coincide with the busiest elective periods, urgent
cases often need to be absorbed into an already active operating
schedule rather than handled in separate capacity.

During weekends, the temporal pattern flattens slightly, yet the
afternoon concentration remains visible. Both Saturday and Sunday show
sustained urgent activity across the day and into the early evening,
reflecting the continuous need for surgical care even when elective
operations are minimal.

Overall, the figure shows that urgent cases, despite being fewer in
number, are strongly clustered within the same hours as routine
operating room use. This temporal overlap can create additional
scheduling pressure during peak times, especially when sudden non
elective cases must be integrated into a full elective program.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/urgency_weekday-1} 

}

\caption{Hourly distribution of non-elective surgery start times by weekday \label{fig:urgency_weekday}}\label{fig:urgency_weekday}
\end{figure}

Elective surgeries dominate weekday activity at Maaseik, as shown in
Table \ref{tab:urgency_wd}, consistently making up 94 to 95 percent of
all procedures from Monday to Friday. The share of non elective
surgeries remains steady across the workweek, between 4.6 and 6.3
percent, indicating a predictable and manageable level of urgent demand.
This stability suggests that urgent cases are routinely absorbed into
the daily schedule without major fluctuations, allowing elective
activity to proceed with limited disruption.

The weekend shows a markedly different pattern. On Saturday, only 41.8
percent of surgeries are elective, and on Sunday this drops to 43.9
percent, meaning that more than half of weekend procedures are non
elective. This sharp shift reflects the reduced elective program on
weekends and the dominant role of urgent or unplanned cases in driving
surgical activity.

Together, these patterns underline a clear operational distinction:
weekdays are primarily shaped by scheduled elective work, whereas
weekends rely heavily on urgent care. Maintaining sufficient flexibility
in staffing, room allocation, and on-call capacity is therefore
essential to handle weekend demand without compromising the stability of
weekday elective operations.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1282}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1923}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2436}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1923}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2436}}@{}}
\caption{Weekday distribution of elective vs.~non-elective surgeries
(Maaseik). \label{tab:urgency_wd}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Elective (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Non-elective (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Elective (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Non-elective (\%)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Weekday
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Elective (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Non-elective (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Elective (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Non-elective (\%)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Ma & 9430 & 502 & 94.9 & 5.1 \\
Di & 11740 & 568 & 95.4 & 4.6 \\
Wo & 8810 & 485 & 94.8 & 5.2 \\
Do & 10726 & 517 & 95.4 & 4.6 \\
Vr & 9839 & 664 & 93.7 & 6.3 \\
Za & 130 & 181 & 41.8 & 58.2 \\
Zo & 136 & 174 & 43.9 & 56.1 \\
\end{longtable}

\subsection{Do urgent cases drive
overtime?}\label{do-urgent-cases-drive-overtime}

Urgent cases contribute to overtime work, but they are not its primary
driver, as shown in Table \ref{tab:afterhours_urgency}. Only 2.1 percent
of elective surgeries extend beyond the scheduled shift, compared with
13.1 percent of non elective ones. Although this difference is
substantial in relative terms, the absolute number of after-hours
elective cases remains far higher because elective activity dominates
the overall surgical volume. This indicates that while urgent cases are
more likely to run into the evening, most after-hours work still
originates from elective procedures.

Average overtime per case is also higher for non elective surgeries.
Urgent cases show a mean extension of 6 minutes, compared with 0.9
minutes for elective ones. The 95th percentile reinforces this pattern,
reaching 44 minutes for non elective surgeries while remaining at 0
minutes for elective ones. These values suggest that when urgent
procedures do extend beyond the shift, they are more likely to require
longer overruns.

Overall, the results imply that unplanned demand does contribute
meaningfully to extended operating hours, but it does not overshadow the
impact of elective cases. Most evening work arises from elective
procedures that exceed their planned durations, while urgent cases
account for a smaller but more intense share of after-hours extensions.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1376}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1101}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1651}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1651}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2018}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2202}}@{}}
\caption{After-hours frequency and overtime duration by urgency type
(Maaseik). \label{tab:afterhours_urgency}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Urgency type
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
After-hours (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
After-hours (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean overtime (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
95th percentile (min)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Urgency type
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
After-hours (n)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
After-hours (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean overtime (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
95th percentile (min)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Elective & 50811 & 1090 & 2.1 & 0.9 & 0 \\
NonElective & 3091 & 404 & 13.1 & 6 & 44 \\
\end{longtable}

\subsection{Do urgent cases interrupt elective
planning?}\label{do-urgent-cases-interrupt-elective-planning}

The results in Table \ref{tab:overlap_swap} show that room swaps among
elective surgeries remain rare, but they occur slightly more often when
an overlap with a non elective case takes place. Among elective
surgeries with no overlap, 0.5 percent involved a room swap, compared
with 1.6 percent among those that coincided with an urgent procedure.
Although the relative difference is noticeable, the absolute frequencies
remain low.

This pattern indicates that while urgent cases occasionally increase
local scheduling pressure, they do not systematically trigger widespread
room reallocations. Instead, overlaps between elective and non elective
activity appear to be handled mainly through short timing adjustments,
coordination between teams, or temporary sequencing changes rather than
by physically moving elective cases to other rooms. Overall, urgent
interventions introduce some operational complexity but do not
substantially disrupt the broader room allocation structure within the
elective program.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2083}}@{}}
\caption{Room swap frequency among elective cases: overlapped vs.~not
overlapped. \label{tab:overlap_swap}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Overlapped
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
N
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
RoomSwaps
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ShareSwapped
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Overlapped
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
N
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
RoomSwaps
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ShareSwapped
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No & 49298 & 224 & 0.5 \\
Yes & 1487 & 24 & 1.6 \\
\end{longtable}

As shown in Table \ref{tab:overlap_days}, overlaps between urgent and
elective surgeries occurred on 456 out of 1174 observed days,
corresponding to 38.8 percent of all days. This sizeable share indicates
that schedule interference is not unusual but a recurring feature of day
to day operations. Although the magnitude and operational impact of each
overlap may differ, their regular occurrence underscores the ongoing
need for flexibility in resource allocation and real time coordination
between planned elective activity and urgent surgical demand.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1944}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}@{}}
\caption{Days with at least one urgent--elective overlap in the same OR.
\label{tab:overlap_days}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OverlapDays
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
TotalDays
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
OverlapDays
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
TotalDays
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SharePct
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
456 & 1174 & 38.8 \\
\end{longtable}

The proportion of elective surgeries affected by urgent overlaps
fluctuates modestly over time, as shown in Figure
\ref{fig:overlap_trend}. Monthly values typically range between 2 and 4
percent, with occasional peaks slightly above this level. A gradual
upward tendency is visible across much of 2023 and into early 2024,
followed by a temporary decline during the second half of 2024. Despite
these month to month variations, the overall level remains relatively
stable. This consistency indicates that interference from urgent cases
is a persistent operational feature rather than a short lived anomaly,
reflecting the regular need to accommodate unplanned demand alongside
scheduled elective activity.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overlap_trend-1} 

}

\caption{Monthly share of elective surgeries affected by urgent overlaps \label{fig:overlap_trend}}\label{fig:overlap_trend}
\end{figure}

As shown in Figure \ref{fig:overlap_hourly}, overlaps between urgent and
elective surgeries occur predominantly during daytime hours. The
frequency rises sharply after 08:00, reaches its highest levels between
13:00 and 15:00, and then declines steadily into the evening. Only a
small number of overlaps occur during the night or early morning. This
temporal pattern mirrors the broader distribution of non elective
surgery starts and confirms that most schedule conflicts arise when
operating room utilization is already at its peak. The concentration of
overlaps in the middle of the day indicates that urgent admissions
frequently coincide with the busiest elective periods, intensifying
competition for operating room capacity during standard working hours.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overlap_hourly-1} 

}

\caption{Hourly frequency of urgent–elective overlaps \label{fig:overlap_hourly}}\label{fig:overlap_hourly}
\end{figure}

Figure \ref{fig:overlap_delay} shows that elective surgeries affected by
an urgent overlap consistently start later than those without overlap.
The gap is especially pronounced in early 2022, when mean start delays
for overlapped cases often exceeded 60 minutes, compared with roughly 20
to 30 minutes for non overlapped cases. Although the difference narrows
somewhat over time, overlapped surgeries remain visibly more delayed
throughout the entire period.

The recurring peaks in the overlapped series suggest that these delays
arise from periodic scheduling pressures rather than isolated incidents.
When urgent demand increases or competing cases accumulate, elective
surgeries that experience an overlap appear particularly vulnerable to
cascading delays. Overall, the figure demonstrates that urgent overlaps
exert a measurable and persistent impact on elective punctuality,
especially during months with high operating room utilization.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/overlap_delay-1} 

}

\caption{Average start delay of elective surgeries by overlap status \label{fig:overlap_delay}}\label{fig:overlap_delay}
\end{figure}

As shown in Table \ref{tab:or_overlap}, the frequency and impact of
overlaps vary substantially across operating rooms. The largest number
of elective cases affected by urgent overlaps occurs in MO06 (323 cases)
and MO03 (272 cases), where 8.6 percent and 7.8 percent of elective
activity, respectively, experience an overlap. These rooms appear to
function as high-volume environments where scheduled and urgent activity
frequently intersect.

Several other ORs, including MKI3, MO04, and MO05, also register
meaningful numbers of overlap events, though at lower relative shares
ranging from 1.8 to 4.7 percent. The smallest proportions are observed
in MKI1, MO01, and MO02, where overlaps affect less than 2 percent of
elective surgeries.

Median start delays show a heterogeneous pattern across rooms. In most
ORs, elective cases with overlaps begin later than comparable cases
without overlap---for instance, median delays increase from 12 to 23
minutes in MO06 and from 15 to 32 minutes in MO03---indicating that
urgent activity frequently disrupts planned schedules. In contrast, a
few rooms such as MKI3 and MO05 display negative or near-zero
differences, suggesting that local rescheduling or capacity adjustments
may allow some elective cases to start earlier than originally
anticipated.

Overall, the results highlight that the operational impact of urgent
cases is concentrated in a small group of high-volume rooms, where
elective and non-elective activity most often coincide. These rooms
experience the strongest scheduling pressures, while lower-volume ORs
encounter urgent--elective overlaps only occasionally.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1165}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0777}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1262}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1262}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2913}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2621}}@{}}
\caption{Operating rooms with urgent--elective overlap.
\label{tab:or_overlap}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
PlannedOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n\_elective
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Med StartDelay (No Overlap)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Med StartDelay (Overlap)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
PlannedOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Count
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
n\_elective
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Percentage
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Med StartDelay (No Overlap)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Med StartDelay (Overlap)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO06 & 323 & 3748 & 8.6 & 12 & 23 \\
MO03 & 272 & 3491 & 7.8 & 15 & 32 \\
MKI3 & 251 & 14151 & 1.8 & -2 & -3 \\
MO04 & 235 & 5025 & 4.7 & 8 & 0 \\
MO05 & 171 & 4000 & 4.3 & 7 & -4 \\
MKI1 & 97 & 8245 & 1.2 & 39 & 47 \\
MO01 & 71 & 3901 & 1.8 & 5 & 9 \\
MO02 & 67 & 8211 & 0.8 & 16 & 15 \\
\end{longtable}

\newpage

\section{How stable is the surgical schedule in
execution?}\label{how-stable-is-the-surgical-schedule-in-execution}

Beyond accurate planning, the stability of the realised schedule is a
key indicator of operational performance in the operating theatre. Even
when planned start times, durations, and room assignments are correct,
day-to-day execution may deviate because of unforeseen delays, emergency
insertions, or coordination issues.

This section evaluates how consistently the planned schedule is
maintained throughout the day by focusing on two complementary aspects:

\begin{itemize}
\tightlist
\item
  \emph{Shift changes}, where surgeries are executed in a different
  shift than originally planned, indicating how often the daily
  programme must be adjusted in real time.
\item
  \emph{Idle or gap times}, representing the pauses between consecutive
  surgeries within the same room, which reflect how efficiently the
  available capacity is utilised.
\end{itemize}

Together, these indicators capture the operational resilience of the OR
complex and the ability to absorb disruptions and maintain smooth
throughput despite variable circumstances. High rates of shift changes
or long idle periods point to latent inefficiencies in daily planning
and coordination, whereas stability across these metrics signals a
well-synchronised workflow.

\subsection{How often are surgeries moved to another
shift?}\label{how-often-are-surgeries-moved-to-another-shift}

Changes between planned and actual shifts occur when surgeries begin
later than scheduled or are rescheduled into a later block of the day.
The actual shift is determined based on the observed start time relative
to the operating department's official shift boundaries (day:
08:00--16:30, evening: 16:30--22:00, night: 22:00--08:00).

At Campus Maaseik, 758 surgeries, or 1.4 percent of all recorded cases,
were performed in a different shift than initially planned, as shown in
Table \ref{tab:shift_mismatch}. For these cases, the average start delay
was 13.3 minutes, indicating that most shift changes arise not from
extreme postponements but from moderate delays that push a case across a
shift boundary. The average procedure duration deviation was -9.2
minutes, meaning that once these surgeries begin, they tend to run
slightly shorter than expected.

The mean overtime for shift-mismatched surgeries was 6.4 minutes,
suggesting that these cases typically do not lead to substantial
extensions into the next shift. Instead, most mismatches appear to
result from cases scheduled near shift transitions or from minor timing
deviations rather than major schedule overruns. Although these cases
constitute a small share of total surgical activity, their occurrence
can still complicate staffing, turnover, and the coordination of
subsequent sessions.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0690}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1379}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1552}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2155}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2328}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1897}}@{}}
\caption{Cases performed in a different shift than planned (Maaseik).
\label{tab:shift_mismatch}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
MismatchCount
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Share moved (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Start Delay (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Duration Diff (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime (min)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
MismatchCount
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Share moved (\%)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Start Delay (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Duration Diff (min)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Mean Overtime (min)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
53902 & 758 & 1.4 & 13.3 & -9.2 & 6.4 \\
\end{longtable}

As shown in Figure \ref{fig:shift_moved_monthly}, the monthly trend
displays noticeable fluctuations but no structural deterioration over
time. In early 2022, the share of surgeries performed in a different
shift initially reached just above 2 percent before stabilizing between
1.2 and 1.8 percent during the rest of the year. Throughout 2023, the
proportion continued to vary within a similar range, with several
short-lived peaks around 2 percent and occasional dips close to 1
percent. A comparable pattern persisted into 2024 and the early months
of 2025, with values generally oscillating between 0.7 and 1.6 percent.
Although month-to-month variability is present, these changes remain
modest and do not indicate any systematic upward trend in shift
mismatches.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/shift_moved_monthly-1} 

}

\caption{Monthly percentage of surgeries moved to another shift \label{fig:shift_moved_monthly}}\label{fig:shift_moved_monthly}
\end{figure}

Overall, the data suggest a moderate improvement in schedule adherence
since 2022, followed by a period of relative stability. The
month-to-month variation likely reflects normal fluctuations in workload
and case mix rather than structural scheduling issues.

\subsection{How much idle time occurs between consecutive
surgeries?}\label{how-much-idle-time-occurs-between-consecutive-surgeries}

Idle or gap time represents the short pause between the end of one
surgery and the start of the next within the same operating room during
the regular day shift (08:00--16:30). It captures how efficiently rooms
are prepared for the next case and how well surgical schedules are
synchronised in daily practice. For each room-day combination, gap time
measures either the delay between shift start and the first case or the
interval between consecutive cases, excluding breaks longer than 60
minutes that reflect planned downtime.

At Campus Maaseik, the average idle time between consecutive surgeries
is 4.1 minutes, while the median is 2 minutes, as shown in Table
\ref{tab:idle_summary}. These low values indicate that room turnover is
generally fast and tightly managed. The interquartile range of 5 minutes
shows that most changeovers occur within a narrow window, with little
variation across cases. The 95th percentile of 15 minutes indicates that
only a small subset of transitions take meaningfully longer, and the
upper extreme of 60 minutes corresponds to the applied cutoff for
excluding planned breaks rather than reflecting typical operational
performance.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0972}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1111}}@{}}
\caption{Summary statistics of idle time between consecutive surgeries
(minutes). \label{tab:idle_summary}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99.9
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IQR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P95
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
P99.9
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
4.1 & 2 & 6.9 & 5 & 0 & 60 & 15 & 38 & 58 \\
\end{longtable}

As shown in Figure \ref{fig:idle_distribution}, the histogram confirms
that most idle intervals are very short. Nearly half of all turnovers
fall below 5 minutes, and roughly three quarters remain under 10
minutes. Beyond that point, the frequency drops sharply, with only a
small number of transitions extending into the 20--30 minute range. The
right-hand tail is thin, reflecting the exclusion of gaps longer than
one hour, which correspond to planned downtime rather than operational
turnover.

Overall, the distribution demonstrates that turnover between consecutive
cases is highly efficient and stable across operating rooms. Short idle
periods dominate the workflow, while occasional longer pauses occur
infrequently and stay well within operational boundaries. These patterns
suggest that changeover processes are tightly managed rather than
indicative of systematic underutilisation.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/idle_distribution-1} 

}

\caption{Distribution of idle time between surgeries (grouped per 5 min) \label{fig:idle_distribution}}\label{fig:idle_distribution}
\end{figure}

\subsection{How does idle time vary across operating
rooms?}\label{how-does-idle-time-vary-across-operating-rooms}

As shown in Figure \ref{fig:idle_or}, the mean and median idle times
vary moderately across operating rooms at Campus Maaseik. In every room,
the median idle time is lower than the mean, confirming that most
intervals between consecutive surgeries are short while a smaller number
of longer pauses pull the average upward. This consistent gap
illustrates the right-skewed nature of idle-time distributions, where
brief turnovers are the norm but longer gaps still appear occasionally.

The absolute differences between rooms are limited. Median values are
tightly grouped, indicating comparable turnover performance across much
of the OR complex. The highest idle times occur in rooms such as MKI1
and MO06, where both mean and median values sit above the overall
pattern. In the remaining rooms, mean and median idle times cluster at
lower levels, reflecting fast and uniform transitions between cases.

Overall, idle time across rooms is contained and stable. The few longer
gaps visible in certain rooms appear to stem from isolated extended
turnovers rather than systematic inefficiencies. The figure therefore
highlights a well-coordinated workflow, with only minor room-to-room
variation in turnover performance.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth,]{In-Depth_Analysis_Maaseik_files/figure-latex/idle_or-1} 

}

\caption{Mean and median idle time per operating room \label{fig:idle_or}}\label{fig:idle_or}
\end{figure}

As shown in Table \ref{tab:idle_variability}, the standard deviation
(SD) and coefficient of variation (CV) describe how much idle times
fluctuate around their typical value for each operating room, sorted by
median idle time. Across most rooms, the SD falls between roughly 5 and
9 minutes, while CV values generally range from about 90 to 150 percent.
These levels indicate that although idle intervals are short, they still
vary meaningfully from case to case.

Some rooms---such as MO03 and MO05---show comparatively higher SD and CV
values, reflecting wider spreads in turnover times and less uniform
changeover performance. In contrast, rooms like MO02, MO01, and MKI3
have lower SDs and CVs, suggesting that their idle times are more
tightly clustered around the median.

Overall, variability in idle time differs across rooms but stays within
a contained range for most of the OR complex. The results confirm that
short turnover intervals are the norm, while only a limited number of
rooms exhibit broader distributions that may reflect more diverse
workflows or less predictable scheduling environments.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1111}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2917}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3750}}@{}}
\caption{Standard deviation and coefficient of variation of idle time
per operating room (minutes), sorted by median idle time.
\label{tab:idle_variability}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Cases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Standard deviation
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Coefficient of variation
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
ActualOR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Cases
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Standard deviation
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Coefficient of variation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
MO05 & 3529 & 7.6 & 114.1 \\
MO03 & 3119 & 8.5 & 129.5 \\
MO06 & 3550 & 7.4 & 126.4 \\
MKI1 & 6994 & 5.8 & 99.3 \\
MO04 & 4354 & 7.2 & 124.1 \\
MO01 & 3343 & 6.2 & 126.6 \\
MO02 & 7594 & 5.5 & 238.1 \\
MKI3 & 12880 & 6.2 & 401.3 \\
\end{longtable}

\section{Conclusion}\label{conclusion}

This analysis of Campus Maaseik provides a detailed and data driven
account of how surgical activity unfolds from planning to execution
within the operating theatre. By examining timing accuracy, room
allocation, after hours activity, urgent case dynamics, shift
transitions, and turnover performance, the report highlights both the
system's strengths and its operational sensitivities.

Across sections, planned and observed durations align well on average,
though notable variability persists between procedure types. Start time
delays are common and tend to accumulate throughout the day,
contributing to later finishing times even when procedure durations
remain close to plan. While the overall program remains reliable, these
small deviations illustrate how tightly sequenced operating room
schedules at Maaseik respond to routine sources of disruption.

After hours activity forms a recurring but contained part of the
workload, with approximately 3.8 percent of surgeries extending beyond
regular operating hours. Most overruns are modest, with median overtime
equal to zero and only a limited share of cases exceeding one hour. A
small number of longer and more complex procedures account for a
disproportionate share of total overtime. Room assignments are highly
stable: room swaps are infrequent and concentrated in a small set of
closely related operating rooms, with minimal downstream impact on
duration or overtime.

Urgent cases represent a modest share of activity, accounting for
roughly 6 percent of surgeries, and frequently coincide with elective
work. Although their overall volume is limited, overlaps occur regularly
throughout the week, underscoring their continuous operational
relevance. These overlaps can introduce start time variability for
elective cases but rarely trigger broader rescheduling or systematic
room reallocation, indicating effective coordination between planned and
unplanned care.

Shift transitions and idle times point to an efficient process.
Approximately 3 to 4 percent of surgeries are performed in a different
shift than originally planned, a small but operationally meaningful
group primarily linked to delays earlier in the day rather than extended
procedure durations. Idle periods between cases remain short and
consistent across rooms, with a median gap time of 2 minutes and limited
variability over time. Turnover is therefore fast and well stabilised,
although a small number of rooms show wider distributions reflecting
lower volumes or more diverse local workflows.

Taken together, the findings present a comprehensive picture of
operating room performance at Campus Maaseik. Surgical planning
generally translates well into real world execution, with a system that
balances predictability and flexibility in a mixed elective and non
elective environment. Opportunities for improvement remain targeted
rather than systemic and relate mainly to stabilising start times,
managing occasional urgent insertions, and smoothing day level
scheduling variability.

\end{document}
